package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteImageHandlerFunc turns a function with the right signature into a delete image handler
type DeleteImageHandlerFunc func(DeleteImageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteImageHandlerFunc) Handle(params DeleteImageParams) middleware.Responder {
	return fn(params)
}

// DeleteImageHandler interface for that can handle valid delete image params
type DeleteImageHandler interface {
	Handle(DeleteImageParams) middleware.Responder
}

// NewDeleteImage creates a new http.Handler for the delete image operation
func NewDeleteImage(ctx *middleware.Context, handler DeleteImageHandler) *DeleteImage {
	return &DeleteImage{Context: ctx, Handler: handler}
}

/*DeleteImage swagger:route DELETE /storage/{store_name}/info/{id} storage deleteImage

Delete an image

Delete an image by id in an image store

*/
type DeleteImage struct {
	Context *middleware.Context
	Handler DeleteImageHandler
}

func (o *DeleteImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewDeleteImageParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
