package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// DeleteImageURL generates an URL for the delete image operation
type DeleteImageURL struct {
	ID        string
	StoreName string

	KeepNodes []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteImageURL) WithBasePath(bp string) *DeleteImageURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteImageURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteImageURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/storage/{store_name}/info/{id}"

	id := o.ID
	if id != "" {
		_path = strings.Replace(_path, "{id}", id, -1)
	} else {
		return nil, errors.New("ID is required on DeleteImageURL")
	}
	storeName := o.StoreName
	if storeName != "" {
		_path = strings.Replace(_path, "{store_name}", storeName, -1)
	} else {
		return nil, errors.New("StoreName is required on DeleteImageURL")
	}
	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var keepNodesIR []string
	for _, keepNodesI := range o.KeepNodes {
		keepNodesIS := keepNodesI
		if keepNodesIS != "" {
			keepNodesIR = append(keepNodesIR, keepNodesIS)
		}
	}

	keepNodes := swag.JoinByFormat(keepNodesIR, "")

	if len(keepNodes) > 0 {
		qsv := keepNodes[0]
		if qsv != "" {
			qs.Set("keepNodes", qsv)
		}
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteImageURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteImageURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteImageURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteImageURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteImageURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteImageURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
