package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vmware/vic/lib/apiservers/portlayer/models"
)

/*ListVolumesOK OK

swagger:response listVolumesOK
*/
type ListVolumesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.VolumeResponse `json:"body,omitempty"`
}

// NewListVolumesOK creates ListVolumesOK with default headers values
func NewListVolumesOK() *ListVolumesOK {
	return &ListVolumesOK{}
}

// WithPayload adds the payload to the list volumes o k response
func (o *ListVolumesOK) WithPayload(payload []*models.VolumeResponse) *ListVolumesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list volumes o k response
func (o *ListVolumesOK) SetPayload(payload []*models.VolumeResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVolumesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.VolumeResponse, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ListVolumesInternalServerError Not found

swagger:response listVolumesInternalServerError
*/
type ListVolumesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListVolumesInternalServerError creates ListVolumesInternalServerError with default headers values
func NewListVolumesInternalServerError() *ListVolumesInternalServerError {
	return &ListVolumesInternalServerError{}
}

// WithPayload adds the payload to the list volumes internal server error response
func (o *ListVolumesInternalServerError) WithPayload(payload *models.Error) *ListVolumesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list volumes internal server error response
func (o *ListVolumesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVolumesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListVolumesDefault error

swagger:response listVolumesDefault
*/
type ListVolumesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListVolumesDefault creates ListVolumesDefault with default headers values
func NewListVolumesDefault(code int) *ListVolumesDefault {
	if code <= 0 {
		code = 500
	}

	return &ListVolumesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list volumes default response
func (o *ListVolumesDefault) WithStatusCode(code int) *ListVolumesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list volumes default response
func (o *ListVolumesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list volumes default response
func (o *ListVolumesDefault) WithPayload(payload *models.Error) *ListVolumesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list volumes default response
func (o *ListVolumesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVolumesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
