package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vmware/vic/lib/apiservers/portlayer/models"
)

/*VolumeStoresListOK OK

swagger:response volumeStoresListOK
*/
type VolumeStoresListOK struct {

	/*
	  In: Body
	*/
	Payload *models.VolumeStoresListResponse `json:"body,omitempty"`
}

// NewVolumeStoresListOK creates VolumeStoresListOK with default headers values
func NewVolumeStoresListOK() *VolumeStoresListOK {
	return &VolumeStoresListOK{}
}

// WithPayload adds the payload to the volume stores list o k response
func (o *VolumeStoresListOK) WithPayload(payload *models.VolumeStoresListResponse) *VolumeStoresListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the volume stores list o k response
func (o *VolumeStoresListOK) SetPayload(payload *models.VolumeStoresListResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VolumeStoresListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*VolumeStoresListNotFound Not found

swagger:response volumeStoresListNotFound
*/
type VolumeStoresListNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewVolumeStoresListNotFound creates VolumeStoresListNotFound with default headers values
func NewVolumeStoresListNotFound() *VolumeStoresListNotFound {
	return &VolumeStoresListNotFound{}
}

// WithPayload adds the payload to the volume stores list not found response
func (o *VolumeStoresListNotFound) WithPayload(payload *models.Error) *VolumeStoresListNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the volume stores list not found response
func (o *VolumeStoresListNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VolumeStoresListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*VolumeStoresListInternalServerError error

swagger:response volumeStoresListInternalServerError
*/
type VolumeStoresListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewVolumeStoresListInternalServerError creates VolumeStoresListInternalServerError with default headers values
func NewVolumeStoresListInternalServerError() *VolumeStoresListInternalServerError {
	return &VolumeStoresListInternalServerError{}
}

// WithPayload adds the payload to the volume stores list internal server error response
func (o *VolumeStoresListInternalServerError) WithPayload(payload *models.Error) *VolumeStoresListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the volume stores list internal server error response
func (o *VolumeStoresListInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VolumeStoresListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
