package scopes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vmware/vic/lib/apiservers/portlayer/models"
)

/*BindContainerOK OK

swagger:response bindContainerOK
*/
type BindContainerOK struct {

	/*
	  In: Body
	*/
	Payload *models.BindContainerResponse `json:"body,omitempty"`
}

// NewBindContainerOK creates BindContainerOK with default headers values
func NewBindContainerOK() *BindContainerOK {
	return &BindContainerOK{}
}

// WithPayload adds the payload to the bind container o k response
func (o *BindContainerOK) WithPayload(payload *models.BindContainerResponse) *BindContainerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the bind container o k response
func (o *BindContainerOK) SetPayload(payload *models.BindContainerResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BindContainerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BindContainerNotFound Not found

swagger:response bindContainerNotFound
*/
type BindContainerNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBindContainerNotFound creates BindContainerNotFound with default headers values
func NewBindContainerNotFound() *BindContainerNotFound {
	return &BindContainerNotFound{}
}

// WithPayload adds the payload to the bind container not found response
func (o *BindContainerNotFound) WithPayload(payload *models.Error) *BindContainerNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the bind container not found response
func (o *BindContainerNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BindContainerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BindContainerInternalServerError error

swagger:response bindContainerInternalServerError
*/
type BindContainerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBindContainerInternalServerError creates BindContainerInternalServerError with default headers values
func NewBindContainerInternalServerError() *BindContainerInternalServerError {
	return &BindContainerInternalServerError{}
}

// WithPayload adds the payload to the bind container internal server error response
func (o *BindContainerInternalServerError) WithPayload(payload *models.Error) *BindContainerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the bind container internal server error response
func (o *BindContainerInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BindContainerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
