package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwarePhotonControllerModelAdaptersRegistryPhotonModelAdaptersRegistryServicePhotonModelAdapterConfig com vmware photon controller model adapters registry photon model adapters registry service photon model adapter config
// swagger:model com:vmware:photon:controller:model:adapters:registry:PhotonModelAdaptersRegistryService:PhotonModelAdapterConfig
type ComVmwarePhotonControllerModelAdaptersRegistryPhotonModelAdaptersRegistryServicePhotonModelAdapterConfig struct {

	// Map with endpoints, given photon adapter provides.The key represents the endpoint type id (e.g. instanceAdapterLink, enumerationAdapterLink, etc) and the value is the actual link (url) of the endpoint
	AdapterEndpoints map[string]string `json:"adapterEndpoints,omitempty"`

	// Custom property bag that can be used to store photon model adapter specific properties.
	CustomProperties map[string]string `json:"customProperties,omitempty"`

	// Identifier of the photon model adapter configuration.
	ID string `json:"id,omitempty"`

	// Name of the photon model adapter configuration.
	Name string `json:"name,omitempty"`
}

// Validate validates this com vmware photon controller model adapters registry photon model adapters registry service photon model adapter config
func (m *ComVmwarePhotonControllerModelAdaptersRegistryPhotonModelAdaptersRegistryServicePhotonModelAdapterConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelAdaptersRegistryPhotonModelAdaptersRegistryServicePhotonModelAdapterConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelAdaptersRegistryPhotonModelAdaptersRegistryServicePhotonModelAdapterConfig) UnmarshalBinary(b []byte) error {
	var res ComVmwarePhotonControllerModelAdaptersRegistryPhotonModelAdaptersRegistryServicePhotonModelAdapterConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
