package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesVolumesDownwardAPIVolumeSource com vmware admiral compute kubernetes entities volumes downward API volume source
// swagger:model com:vmware:admiral:compute:kubernetes:entities:volumes:DownwardAPIVolumeSource
type ComVmwareAdmiralComputeKubernetesEntitiesVolumesDownwardAPIVolumeSource struct {

	// default mode
	DefaultMode int64 `json:"defaultMode,omitempty"`

	// items
	Items []*ComVmwareAdmiralComputeKubernetesEntitiesVolumesDownwardAPIVolumeFile `json:"items"`
}

// Validate validates this com vmware admiral compute kubernetes entities volumes downward API volume source
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesDownwardAPIVolumeSource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateItems(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesDownwardAPIVolumeSource) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(m.Items) { // not required
		return nil
	}

	for i := 0; i < len(m.Items); i++ {

		if swag.IsZero(m.Items[i]) { // not required
			continue
		}

		if m.Items[i] != nil {

			if err := m.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesDownwardAPIVolumeSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesDownwardAPIVolumeSource) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesVolumesDownwardAPIVolumeSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
