package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState com vmware admiral request compute compute removal task service compute removal task state
// swagger:model com:vmware:admiral:request:compute:ComputeRemovalTaskService:ComputeRemovalTaskState
type ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState struct {

	// Custom properties.
	CustomProperties map[string]string `json:"customProperties,omitempty"`

	// link to a service that will receive updates when the task changes state.
	RequestTrackerLink string `json:"requestTrackerLink,omitempty"`

	// The compute resources to be removed
	ResourceLinks []string `json:"resourceLinks"`

	// Optional resource removal options
	ResourceRemovalOptions []string `json:"resourceRemovalOptions"`

	// Callback link and response from the service initiated this task.
	ServiceTaskCallback *ComVmwareAdmiralServiceCommonServiceTaskCallback `json:"serviceTaskCallback,omitempty"`

	// Whether to skip the associated reservation or not
	SkipReleaseResourceQuota bool `json:"skipReleaseResourceQuota,omitempty"`

	//  Describes a service task state.
	TaskInfo *ComVmwareXenonCommonTaskState `json:"taskInfo,omitempty"`

	//  Describes a service task sub stage.
	TaskSubStage string `json:"taskSubStage,omitempty"`

	// tenant links
	TenantLinks []string `json:"tenantLinks"`
}

// Validate validates this com vmware admiral request compute compute removal task service compute removal task state
func (m *ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateResourceRemovalOptions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateServiceTaskCallback(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTaskInfo(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTenantLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState) validateResourceLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceLinks) { // not required
		return nil
	}

	return nil
}

var comVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskStateResourceRemovalOptionsItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DOCUMENT_CHANGES_ONLY","VALIDATE_ONLY","IS_MOCK","PRESERVE_MISSING_RESOUCES","SELF_DELETE_ON_COMPLETION"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		comVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskStateResourceRemovalOptionsItemsEnum = append(comVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskStateResourceRemovalOptionsItemsEnum, v)
	}
}

func (m *ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState) validateResourceRemovalOptionsItemsEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, comVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskStateResourceRemovalOptionsItemsEnum); err != nil {
		return err
	}
	return nil
}

func (m *ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState) validateResourceRemovalOptions(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceRemovalOptions) { // not required
		return nil
	}

	for i := 0; i < len(m.ResourceRemovalOptions); i++ {

		// value enum
		if err := m.validateResourceRemovalOptionsItemsEnum("resourceRemovalOptions"+"."+strconv.Itoa(i), "body", m.ResourceRemovalOptions[i]); err != nil {
			return err
		}

	}

	return nil
}

func (m *ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState) validateServiceTaskCallback(formats strfmt.Registry) error {

	if swag.IsZero(m.ServiceTaskCallback) { // not required
		return nil
	}

	if m.ServiceTaskCallback != nil {

		if err := m.ServiceTaskCallback.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("serviceTaskCallback")
			}
			return err
		}
	}

	return nil
}

func (m *ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState) validateTaskInfo(formats strfmt.Registry) error {

	if swag.IsZero(m.TaskInfo) { // not required
		return nil
	}

	if m.TaskInfo != nil {

		if err := m.TaskInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("taskInfo")
			}
			return err
		}
	}

	return nil
}

func (m *ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState) validateTenantLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantLinks) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralRequestComputeComputeRemovalTaskServiceComputeRemovalTaskState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
