package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralServiceCommonServiceTaskCallback com vmware admiral service common service task callback
// swagger:model com:vmware:admiral:service:common:ServiceTaskCallback
type ComVmwareAdmiralServiceCommonServiceTaskCallback struct {

	// service self link
	ServiceSelfLink string `json:"serviceSelfLink,omitempty"`
}

// Validate validates this com vmware admiral service common service task callback
func (m *ComVmwareAdmiralServiceCommonServiceTaskCallback) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralServiceCommonServiceTaskCallback) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralServiceCommonServiceTaskCallback) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralServiceCommonServiceTaskCallback
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
