package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwarePhotonControllerModelTasksEndpointAllocationTaskServiceResourceEnumerationRequest com vmware photon controller model tasks endpoint allocation task service resource enumeration request
// swagger:model com:vmware:photon:controller:model:tasks:EndpointAllocationTaskService:ResourceEnumerationRequest
type ComVmwarePhotonControllerModelTasksEndpointAllocationTaskServiceResourceEnumerationRequest struct {

	// delay micros
	DelayMicros int64 `json:"delayMicros,omitempty"`

	// refresh interval micros
	RefreshIntervalMicros int64 `json:"refreshIntervalMicros,omitempty"`

	// resource pool link
	ResourcePoolLink string `json:"resourcePoolLink,omitempty"`
}

// Validate validates this com vmware photon controller model tasks endpoint allocation task service resource enumeration request
func (m *ComVmwarePhotonControllerModelTasksEndpointAllocationTaskServiceResourceEnumerationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelTasksEndpointAllocationTaskServiceResourceEnumerationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelTasksEndpointAllocationTaskServiceResourceEnumerationRequest) UnmarshalBinary(b []byte) error {
	var res ComVmwarePhotonControllerModelTasksEndpointAllocationTaskServiceResourceEnumerationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
