package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeContainerVolumeContainerVolumeDescriptionServiceContainerVolumeDescription com vmware admiral compute container volume container volume description service container volume description
// swagger:model com:vmware:admiral:compute:container:volume:ContainerVolumeDescriptionService:ContainerVolumeDescription
type ComVmwareAdmiralComputeContainerVolumeContainerVolumeDescriptionServiceContainerVolumeDescription struct {

	// creation time micros
	CreationTimeMicros int64 `json:"creationTimeMicros,omitempty"`

	// custom properties
	CustomProperties map[string]string `json:"customProperties,omitempty"`

	// desc
	Desc string `json:"desc,omitempty"`

	// Name of the volume driver to use. Defaults to local for the name.
	Driver string `json:"driver,omitempty"`

	// Composite Template use only. If set to true, specifies that this volume exists outside of the Composite Template.
	External bool `json:"external,omitempty"`

	// Composite Template use only. The name of the external volume. If set then the value of the attribute 'external' is considered 'true'.
	ExternalName string `json:"externalName,omitempty"`

	// group links
	GroupLinks []string `json:"groupLinks"`

	// id
	ID string `json:"id,omitempty"`

	// Defines which adapter will serve the provision request
	InstanceAdapterReference strfmt.URI `json:"instanceAdapterReference,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// A map of field-value pairs for a given volume. These are usedto specify volume options that are used by the volume drivers.
	Options map[string]string `json:"options,omitempty"`

	// Link to the parent volume description.
	ParentDescriptionLink string `json:"parentDescriptionLink,omitempty"`

	// region Id
	RegionID string `json:"regionId,omitempty"`

	// tag links
	TagLinks []string `json:"tagLinks"`

	// tenant links
	TenantLinks []string `json:"tenantLinks"`
}

// Validate validates this com vmware admiral compute container volume container volume description service container volume description
func (m *ComVmwareAdmiralComputeContainerVolumeContainerVolumeDescriptionServiceContainerVolumeDescription) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroupLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTagLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTenantLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeContainerVolumeContainerVolumeDescriptionServiceContainerVolumeDescription) validateGroupLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.GroupLinks) { // not required
		return nil
	}

	return nil
}

func (m *ComVmwareAdmiralComputeContainerVolumeContainerVolumeDescriptionServiceContainerVolumeDescription) validateTagLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TagLinks) { // not required
		return nil
	}

	return nil
}

func (m *ComVmwareAdmiralComputeContainerVolumeContainerVolumeDescriptionServiceContainerVolumeDescription) validateTenantLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantLinks) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContainerVolumeContainerVolumeDescriptionServiceContainerVolumeDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContainerVolumeContainerVolumeDescriptionServiceContainerVolumeDescription) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeContainerVolumeContainerVolumeDescriptionServiceContainerVolumeDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
