package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesVolumesKeyToPath com vmware admiral compute kubernetes entities volumes key to path
// swagger:model com:vmware:admiral:compute:kubernetes:entities:volumes:KeyToPath
type ComVmwareAdmiralComputeKubernetesEntitiesVolumesKeyToPath struct {

	// key
	Key string `json:"key,omitempty"`

	// mode
	Mode int64 `json:"mode,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities volumes key to path
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesKeyToPath) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesKeyToPath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesKeyToPath) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesVolumesKeyToPath
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
