package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeContentBindingBindingPlaceholder com vmware admiral compute content binding binding placeholder
// swagger:model com:vmware:admiral:compute:content:Binding:BindingPlaceholder
type ComVmwareAdmiralComputeContentBindingBindingPlaceholder struct {

	// binding expression
	BindingExpression string `json:"bindingExpression,omitempty"`

	// default value
	DefaultValue string `json:"defaultValue,omitempty"`
}

// Validate validates this com vmware admiral compute content binding binding placeholder
func (m *ComVmwareAdmiralComputeContentBindingBindingPlaceholder) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContentBindingBindingPlaceholder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContentBindingBindingPlaceholder) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeContentBindingBindingPlaceholder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
