package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwarePhotonControllerModelSupportCertificateInfo com vmware photon controller model support certificate info
// swagger:model com:vmware:photon:controller:model:support:CertificateInfo
type ComVmwarePhotonControllerModelSupportCertificateInfo struct {

	// certificate
	Certificate string `json:"certificate,omitempty"`

	// properties
	Properties map[string]string `json:"properties,omitempty"`
}

// Validate validates this com vmware photon controller model support certificate info
func (m *ComVmwarePhotonControllerModelSupportCertificateInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelSupportCertificateInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelSupportCertificateInfo) UnmarshalBinary(b []byte) error {
	var res ComVmwarePhotonControllerModelSupportCertificateInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
