package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState com vmware photon controller model tasks provision network task service provision network task state
// swagger:model com:vmware:photon:controller:model:tasks:ProvisionNetworkTaskService:ProvisionNetworkTaskState
type ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState struct {

	// failure message
	FailureMessage string `json:"failureMessage,omitempty"`

	// is mock request
	IsMockRequest bool `json:"isMockRequest,omitempty"`

	// network description link
	NetworkDescriptionLink string `json:"networkDescriptionLink,omitempty"`

	// request type
	RequestType string `json:"requestType,omitempty"`

	// task info
	TaskInfo *ComVmwareXenonCommonTaskState `json:"taskInfo,omitempty"`

	// task sub stage
	TaskSubStage string `json:"taskSubStage,omitempty"`

	// tenant links
	TenantLinks []string `json:"tenantLinks"`
}

// Validate validates this com vmware photon controller model tasks provision network task service provision network task state
func (m *ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequestType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTaskInfo(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTaskSubStage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTenantLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var comVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTypeRequestTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CREATE","DELETE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		comVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTypeRequestTypePropEnum = append(comVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTypeRequestTypePropEnum, v)
	}
}

const (
	// ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateRequestTypeCREATE captures enum value "CREATE"
	ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateRequestTypeCREATE string = "CREATE"
	// ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateRequestTypeDELETE captures enum value "DELETE"
	ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateRequestTypeDELETE string = "DELETE"
)

// prop value enum
func (m *ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState) validateRequestTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, comVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTypeRequestTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState) validateRequestType(formats strfmt.Registry) error {

	if swag.IsZero(m.RequestType) { // not required
		return nil
	}

	// value enum
	if err := m.validateRequestTypeEnum("requestType", "body", m.RequestType); err != nil {
		return err
	}

	return nil
}

func (m *ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState) validateTaskInfo(formats strfmt.Registry) error {

	if swag.IsZero(m.TaskInfo) { // not required
		return nil
	}

	if m.TaskInfo != nil {

		if err := m.TaskInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("taskInfo")
			}
			return err
		}
	}

	return nil
}

var comVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTypeTaskSubStagePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CREATED","PROVISIONING_NETWORK","FINISHED","FAILED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		comVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTypeTaskSubStagePropEnum = append(comVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTypeTaskSubStagePropEnum, v)
	}
}

const (
	// ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTaskSubStageCREATED captures enum value "CREATED"
	ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTaskSubStageCREATED string = "CREATED"
	// ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTaskSubStagePROVISIONINGNETWORK captures enum value "PROVISIONING_NETWORK"
	ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTaskSubStagePROVISIONINGNETWORK string = "PROVISIONING_NETWORK"
	// ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTaskSubStageFINISHED captures enum value "FINISHED"
	ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTaskSubStageFINISHED string = "FINISHED"
	// ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTaskSubStageFAILED captures enum value "FAILED"
	ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTaskSubStageFAILED string = "FAILED"
)

// prop value enum
func (m *ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState) validateTaskSubStageEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, comVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskStateTypeTaskSubStagePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState) validateTaskSubStage(formats strfmt.Registry) error {

	if swag.IsZero(m.TaskSubStage) { // not required
		return nil
	}

	// value enum
	if err := m.validateTaskSubStageEnum("taskSubStage", "body", m.TaskSubStage); err != nil {
		return err
	}

	return nil
}

func (m *ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState) validateTenantLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantLinks) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState) UnmarshalBinary(b []byte) error {
	var res ComVmwarePhotonControllerModelTasksProvisionNetworkTaskServiceProvisionNetworkTaskState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
