package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralServiceCommonResourceNamePrefixServiceResourceNamePrefixState com vmware admiral service common resource name prefix service resource name prefix state
// swagger:model com:vmware:admiral:service:common:ResourceNamePrefixService:ResourceNamePrefixState
type ComVmwareAdmiralServiceCommonResourceNamePrefixServiceResourceNamePrefixState struct {

	// Flag indicating whether to add additional generated token to the  sequence.
	AddRandomToken bool `json:"addRandomToken,omitempty"`

	// The number where the prefix sequence will begin.
	NextNumber int64 `json:"nextNumber,omitempty"`

	// The amount of ending digits
	NumberOfDigits int64 `json:"numberOfDigits,omitempty"`

	// Prefix or suffix name
	Prefix string `json:"prefix,omitempty"`

	// tenant links
	TenantLinks []string `json:"tenantLinks"`
}

// Validate validates this com vmware admiral service common resource name prefix service resource name prefix state
func (m *ComVmwareAdmiralServiceCommonResourceNamePrefixServiceResourceNamePrefixState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTenantLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralServiceCommonResourceNamePrefixServiceResourceNamePrefixState) validateTenantLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantLinks) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralServiceCommonResourceNamePrefixServiceResourceNamePrefixState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralServiceCommonResourceNamePrefixServiceResourceNamePrefixState) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralServiceCommonResourceNamePrefixServiceResourceNamePrefixState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
