package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState com vmware photon controller model tasks endpoint removal task service endpoint removal task state
// swagger:model com:vmware:photon:controller:model:tasks:EndpointRemovalTaskService:EndpointRemovalTaskState
type ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState struct {

	// A link to endpoint to be deleted.
	EndpointLink string `json:"endpointLink,omitempty"`

	// error threshold
	ErrorThreshold float64 `json:"errorThreshold,omitempty"`

	// failure message
	FailureMessage string `json:"failureMessage,omitempty"`

	// options
	Options []string `json:"options"`

	// task info
	TaskInfo *ComVmwareXenonCommonTaskState `json:"taskInfo,omitempty"`

	// A list of tenant links which can access this task.
	TenantLinks []string `json:"tenantLinks"`
}

// Validate validates this com vmware photon controller model tasks endpoint removal task service endpoint removal task state
func (m *ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOptions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTaskInfo(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTenantLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var comVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskStateOptionsItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DOCUMENT_CHANGES_ONLY","VALIDATE_ONLY","IS_MOCK","PRESERVE_MISSING_RESOUCES","SELF_DELETE_ON_COMPLETION"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		comVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskStateOptionsItemsEnum = append(comVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskStateOptionsItemsEnum, v)
	}
}

func (m *ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState) validateOptionsItemsEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, comVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskStateOptionsItemsEnum); err != nil {
		return err
	}
	return nil
}

func (m *ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState) validateOptions(formats strfmt.Registry) error {

	if swag.IsZero(m.Options) { // not required
		return nil
	}

	for i := 0; i < len(m.Options); i++ {

		// value enum
		if err := m.validateOptionsItemsEnum("options"+"."+strconv.Itoa(i), "body", m.Options[i]); err != nil {
			return err
		}

	}

	return nil
}

func (m *ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState) validateTaskInfo(formats strfmt.Registry) error {

	if swag.IsZero(m.TaskInfo) { // not required
		return nil
	}

	if m.TaskInfo != nil {

		if err := m.TaskInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("taskInfo")
			}
			return err
		}
	}

	return nil
}

func (m *ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState) validateTenantLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantLinks) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState) UnmarshalBinary(b []byte) error {
	var res ComVmwarePhotonControllerModelTasksEndpointRemovalTaskServiceEndpointRemovalTaskState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
