package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeContentBinding com vmware admiral compute content binding
// swagger:model com:vmware:admiral:compute:content:Binding
type ComVmwareAdmiralComputeContentBinding struct {

	// original field expression
	OriginalFieldExpression string `json:"originalFieldExpression,omitempty"`

	// placeholder
	Placeholder *ComVmwareAdmiralComputeContentBindingBindingPlaceholder `json:"placeholder,omitempty"`

	// target field path
	TargetFieldPath []string `json:"targetFieldPath"`
}

// Validate validates this com vmware admiral compute content binding
func (m *ComVmwareAdmiralComputeContentBinding) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlaceholder(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTargetFieldPath(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeContentBinding) validatePlaceholder(formats strfmt.Registry) error {

	if swag.IsZero(m.Placeholder) { // not required
		return nil
	}

	if m.Placeholder != nil {

		if err := m.Placeholder.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("placeholder")
			}
			return err
		}
	}

	return nil
}

func (m *ComVmwareAdmiralComputeContentBinding) validateTargetFieldPath(formats strfmt.Registry) error {

	if swag.IsZero(m.TargetFieldPath) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContentBinding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContentBinding) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeContentBinding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
