package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesVolumesQuobyteVolumeSource com vmware admiral compute kubernetes entities volumes quobyte volume source
// swagger:model com:vmware:admiral:compute:kubernetes:entities:volumes:QuobyteVolumeSource
type ComVmwareAdmiralComputeKubernetesEntitiesVolumesQuobyteVolumeSource struct {

	// group
	Group string `json:"group,omitempty"`

	// read only
	ReadOnly bool `json:"readOnly,omitempty"`

	// registry
	Registry string `json:"registry,omitempty"`

	// user
	User string `json:"user,omitempty"`

	// volume
	Volume string `json:"volume,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities volumes quobyte volume source
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesQuobyteVolumeSource) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesQuobyteVolumeSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesQuobyteVolumeSource) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesVolumesQuobyteVolumeSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
