package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesCommonLabelSelectorRequirement com vmware admiral compute kubernetes entities common label selector requirement
// swagger:model com:vmware:admiral:compute:kubernetes:entities:common:LabelSelectorRequirement
type ComVmwareAdmiralComputeKubernetesEntitiesCommonLabelSelectorRequirement struct {

	// key
	Key string `json:"key,omitempty"`

	// operator
	Operator string `json:"operator,omitempty"`

	// values
	Values []string `json:"values"`
}

// Validate validates this com vmware admiral compute kubernetes entities common label selector requirement
func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonLabelSelectorRequirement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValues(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonLabelSelectorRequirement) validateValues(formats strfmt.Registry) error {

	if swag.IsZero(m.Values) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonLabelSelectorRequirement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonLabelSelectorRequirement) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesCommonLabelSelectorRequirement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
