package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralServiceCommonLogServiceLogServiceState com vmware admiral service common log service log service state
// swagger:model com:vmware:admiral:service:common:LogService:LogServiceState
type ComVmwareAdmiralServiceCommonLogServiceLogServiceState struct {

	// Stream of container log data.
	Logs io.ReadCloser `json:"logs,omitempty"`

	// tenant links
	TenantLinks []string `json:"tenantLinks"`
}

// Validate validates this com vmware admiral service common log service log service state
func (m *ComVmwareAdmiralServiceCommonLogServiceLogServiceState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTenantLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralServiceCommonLogServiceLogServiceState) validateTenantLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantLinks) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralServiceCommonLogServiceLogServiceState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralServiceCommonLogServiceLogServiceState) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralServiceCommonLogServiceLogServiceState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
