package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesPodsLifecycle com vmware admiral compute kubernetes entities pods lifecycle
// swagger:model com:vmware:admiral:compute:kubernetes:entities:pods:Lifecycle
type ComVmwareAdmiralComputeKubernetesEntitiesPodsLifecycle struct {

	// pod start
	PodStart *ComVmwareAdmiralComputeKubernetesEntitiesCommonHandler `json:"podStart,omitempty"`

	// pre stop
	PreStop *ComVmwareAdmiralComputeKubernetesEntitiesCommonHandler `json:"preStop,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities pods lifecycle
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsLifecycle) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePodStart(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePreStop(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsLifecycle) validatePodStart(formats strfmt.Registry) error {

	if swag.IsZero(m.PodStart) { // not required
		return nil
	}

	if m.PodStart != nil {

		if err := m.PodStart.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("podStart")
			}
			return err
		}
	}

	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsLifecycle) validatePreStop(formats strfmt.Registry) error {

	if swag.IsZero(m.PreStop) { // not required
		return nil
	}

	if m.PreStop != nil {

		if err := m.PreStop.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("preStop")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsLifecycle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsLifecycle) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesPodsLifecycle
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
