package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStateTerminated com vmware admiral compute kubernetes entities pods container state terminated
// swagger:model com:vmware:admiral:compute:kubernetes:entities:pods:ContainerStateTerminated
type ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStateTerminated struct {

	// container ID
	ContainerID string `json:"containerID,omitempty"`

	// exit code
	ExitCode int64 `json:"exitCode,omitempty"`

	// finished at
	FinishedAt string `json:"finishedAt,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// signal
	Signal int64 `json:"signal,omitempty"`

	// started at
	StartedAt string `json:"startedAt,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities pods container state terminated
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStateTerminated) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStateTerminated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStateTerminated) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStateTerminated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
