package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareXenonServicesCommonResourceGroupServiceResourceGroupState com vmware xenon services common resource group service resource group state
// swagger:model com:vmware:xenon:services:common:ResourceGroupService:ResourceGroupState
type ComVmwareXenonServicesCommonResourceGroupServiceResourceGroupState struct {

	// query
	Query *ComVmwareXenonServicesCommonQueryTaskQuery `json:"query,omitempty"`
}

// Validate validates this com vmware xenon services common resource group service resource group state
func (m *ComVmwareXenonServicesCommonResourceGroupServiceResourceGroupState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQuery(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareXenonServicesCommonResourceGroupServiceResourceGroupState) validateQuery(formats strfmt.Registry) error {

	if swag.IsZero(m.Query) { // not required
		return nil
	}

	if m.Query != nil {

		if err := m.Query.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("query")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareXenonServicesCommonResourceGroupServiceResourceGroupState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareXenonServicesCommonResourceGroupServiceResourceGroupState) UnmarshalBinary(b []byte) error {
	var res ComVmwareXenonServicesCommonResourceGroupServiceResourceGroupState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
