package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesDeploymentsDeploymentStatus com vmware admiral compute kubernetes entities deployments deployment status
// swagger:model com:vmware:admiral:compute:kubernetes:entities:deployments:DeploymentStatus
type ComVmwareAdmiralComputeKubernetesEntitiesDeploymentsDeploymentStatus struct {

	// available replicas
	AvailableReplicas int64 `json:"availableReplicas,omitempty"`

	// conditions
	Conditions []*ComVmwareAdmiralComputeKubernetesEntitiesDeploymentsDeploymentCondition `json:"conditions"`

	// observed generation
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// ready replicas
	ReadyReplicas int64 `json:"readyReplicas,omitempty"`

	// replicas
	Replicas int64 `json:"replicas,omitempty"`

	// unavailable replicas
	UnavailableReplicas int64 `json:"unavailableReplicas,omitempty"`

	// updated replicas
	UpdatedReplicas int64 `json:"updatedReplicas,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities deployments deployment status
func (m *ComVmwareAdmiralComputeKubernetesEntitiesDeploymentsDeploymentStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConditions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesEntitiesDeploymentsDeploymentStatus) validateConditions(formats strfmt.Registry) error {

	if swag.IsZero(m.Conditions) { // not required
		return nil
	}

	for i := 0; i < len(m.Conditions); i++ {

		if swag.IsZero(m.Conditions[i]) { // not required
			continue
		}

		if m.Conditions[i] != nil {

			if err := m.Conditions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("conditions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesDeploymentsDeploymentStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesDeploymentsDeploymentStatus) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesDeploymentsDeploymentStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
