package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwarePhotonControllerModelResourcesLoadBalancerDescriptionServiceLoadBalancerDescriptionHealthCheckConfiguration com vmware photon controller model resources load balancer description service load balancer description health check configuration
// swagger:model com:vmware:photon:controller:model:resources:LoadBalancerDescriptionService:LoadBalancerDescription:HealthCheckConfiguration
type ComVmwarePhotonControllerModelResourcesLoadBalancerDescriptionServiceLoadBalancerDescriptionHealthCheckConfiguration struct {

	// healthy threshold
	HealthyThreshold int64 `json:"healthyThreshold,omitempty"`

	// interval seconds
	IntervalSeconds int64 `json:"intervalSeconds,omitempty"`

	// port
	Port string `json:"port,omitempty"`

	// protocol
	Protocol string `json:"protocol,omitempty"`

	// timeout seconds
	TimeoutSeconds int64 `json:"timeoutSeconds,omitempty"`

	// unhealthy threshold
	UnhealthyThreshold int64 `json:"unhealthyThreshold,omitempty"`

	// url path
	URLPath string `json:"urlPath,omitempty"`
}

// Validate validates this com vmware photon controller model resources load balancer description service load balancer description health check configuration
func (m *ComVmwarePhotonControllerModelResourcesLoadBalancerDescriptionServiceLoadBalancerDescriptionHealthCheckConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelResourcesLoadBalancerDescriptionServiceLoadBalancerDescriptionHealthCheckConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelResourcesLoadBalancerDescriptionServiceLoadBalancerDescriptionHealthCheckConfiguration) UnmarshalBinary(b []byte) error {
	var res ComVmwarePhotonControllerModelResourcesLoadBalancerDescriptionServiceLoadBalancerDescriptionHealthCheckConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
