package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesVolumesPhotonPersistentDiskVolumeSource com vmware admiral compute kubernetes entities volumes photon persistent disk volume source
// swagger:model com:vmware:admiral:compute:kubernetes:entities:volumes:PhotonPersistentDiskVolumeSource
type ComVmwareAdmiralComputeKubernetesEntitiesVolumesPhotonPersistentDiskVolumeSource struct {

	// fs type
	FsType string `json:"fsType,omitempty"`

	// pd ID
	PdID string `json:"pdID,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities volumes photon persistent disk volume source
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesPhotonPersistentDiskVolumeSource) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesPhotonPersistentDiskVolumeSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesPhotonPersistentDiskVolumeSource) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesVolumesPhotonPersistentDiskVolumeSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
