package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwarePhotonControllerModelTasksServiceTaskCallback com vmware photon controller model tasks service task callback
// swagger:model com:vmware:photon:controller:model:tasks:ServiceTaskCallback
type ComVmwarePhotonControllerModelTasksServiceTaskCallback struct {

	// service URI
	ServiceURI strfmt.URI `json:"serviceURI,omitempty"`
}

// Validate validates this com vmware photon controller model tasks service task callback
func (m *ComVmwarePhotonControllerModelTasksServiceTaskCallback) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelTasksServiceTaskCallback) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwarePhotonControllerModelTasksServiceTaskCallback) UnmarshalBinary(b []byte) error {
	var res ComVmwarePhotonControllerModelTasksServiceTaskCallback
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
