package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesServicesLoadBalancerStatus com vmware admiral compute kubernetes entities services load balancer status
// swagger:model com:vmware:admiral:compute:kubernetes:entities:services:LoadBalancerStatus
type ComVmwareAdmiralComputeKubernetesEntitiesServicesLoadBalancerStatus struct {

	// ingress
	Ingress []*ComVmwareAdmiralComputeKubernetesEntitiesServicesLoadBalancerIngress `json:"ingress"`
}

// Validate validates this com vmware admiral compute kubernetes entities services load balancer status
func (m *ComVmwareAdmiralComputeKubernetesEntitiesServicesLoadBalancerStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIngress(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesEntitiesServicesLoadBalancerStatus) validateIngress(formats strfmt.Registry) error {

	if swag.IsZero(m.Ingress) { // not required
		return nil
	}

	for i := 0; i < len(m.Ingress); i++ {

		if swag.IsZero(m.Ingress[i]) { // not required
			continue
		}

		if m.Ingress[i] != nil {

			if err := m.Ingress[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ingress" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesServicesLoadBalancerStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesServicesLoadBalancerStatus) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesServicesLoadBalancerStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
