package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStatus com vmware admiral compute kubernetes entities pods container status
// swagger:model com:vmware:admiral:compute:kubernetes:entities:pods:ContainerStatus
type ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStatus struct {

	// container ID
	ContainerID string `json:"containerID,omitempty"`

	// image
	Image string `json:"image,omitempty"`

	// image ID
	ImageID string `json:"imageID,omitempty"`

	// last state
	LastState *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerState `json:"lastState,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// ready
	Ready bool `json:"ready,omitempty"`

	// restart count
	RestartCount int64 `json:"restartCount,omitempty"`

	// state
	State *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerState `json:"state,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities pods container status
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastState(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStatus) validateLastState(formats strfmt.Registry) error {

	if swag.IsZero(m.LastState) { // not required
		return nil
	}

	if m.LastState != nil {

		if err := m.LastState.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lastState")
			}
			return err
		}
	}

	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStatus) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	if m.State != nil {

		if err := m.State.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("state")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStatus) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesPodsContainerStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
