package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesVolumesHostPathVolumeSource com vmware admiral compute kubernetes entities volumes host path volume source
// swagger:model com:vmware:admiral:compute:kubernetes:entities:volumes:HostPathVolumeSource
type ComVmwareAdmiralComputeKubernetesEntitiesVolumesHostPathVolumeSource struct {

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities volumes host path volume source
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesHostPathVolumeSource) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesHostPathVolumeSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesHostPathVolumeSource) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesVolumesHostPathVolumeSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
