package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesCommonResourceRequirements com vmware admiral compute kubernetes entities common resource requirements
// swagger:model com:vmware:admiral:compute:kubernetes:entities:common:ResourceRequirements
type ComVmwareAdmiralComputeKubernetesEntitiesCommonResourceRequirements struct {

	// limits
	Limits map[string]string `json:"limits,omitempty"`

	// requests
	Requests map[string]string `json:"requests,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities common resource requirements
func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonResourceRequirements) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonResourceRequirements) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonResourceRequirements) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesCommonResourceRequirements
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
