package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesPodsPodSecurityContext com vmware admiral compute kubernetes entities pods pod security context
// swagger:model com:vmware:admiral:compute:kubernetes:entities:pods:PodSecurityContext
type ComVmwareAdmiralComputeKubernetesEntitiesPodsPodSecurityContext struct {

	// fs group
	FsGroup int64 `json:"fsGroup,omitempty"`

	// run as non root
	RunAsNonRoot bool `json:"runAsNonRoot,omitempty"`

	// run as user
	RunAsUser int64 `json:"runAsUser,omitempty"`

	// supplemental groups
	SupplementalGroups []int64 `json:"supplementalGroups"`
}

// Validate validates this com vmware admiral compute kubernetes entities pods pod security context
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsPodSecurityContext) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSupplementalGroups(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsPodSecurityContext) validateSupplementalGroups(formats strfmt.Registry) error {

	if swag.IsZero(m.SupplementalGroups) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsPodSecurityContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesPodsPodSecurityContext) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesPodsPodSecurityContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
