package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeContainerHostPortProfileServiceHostPortProfileState com vmware admiral compute container host port profile service host port profile state
// swagger:model com:vmware:admiral:compute:container:HostPortProfileService:HostPortProfileState
type ComVmwareAdmiralComputeContainerHostPortProfileServiceHostPortProfileState struct {

	// creation time micros
	CreationTimeMicros int64 `json:"creationTimeMicros,omitempty"`

	// custom properties
	CustomProperties map[string]string `json:"customProperties,omitempty"`

	// desc
	Desc string `json:"desc,omitempty"`

	// Host port profile range end port.
	EndPort int64 `json:"endPort,omitempty"`

	// group links
	GroupLinks []string `json:"groupLinks"`

	// The link of the ComputeState associated with this host port profile.
	HostLink string `json:"hostLink,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// region Id
	RegionID string `json:"regionId,omitempty"`

	// Host port to container link map.
	ReservedPorts map[string]string `json:"reservedPorts,omitempty"`

	// Host port profile range start port.
	StartPort int64 `json:"startPort,omitempty"`

	// tag links
	TagLinks []string `json:"tagLinks"`

	// tenant links
	TenantLinks []string `json:"tenantLinks"`
}

// Validate validates this com vmware admiral compute container host port profile service host port profile state
func (m *ComVmwareAdmiralComputeContainerHostPortProfileServiceHostPortProfileState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroupLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTagLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTenantLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeContainerHostPortProfileServiceHostPortProfileState) validateGroupLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.GroupLinks) { // not required
		return nil
	}

	return nil
}

func (m *ComVmwareAdmiralComputeContainerHostPortProfileServiceHostPortProfileState) validateTagLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TagLinks) { // not required
		return nil
	}

	return nil
}

func (m *ComVmwareAdmiralComputeContainerHostPortProfileServiceHostPortProfileState) validateTenantLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantLinks) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContainerHostPortProfileServiceHostPortProfileState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContainerHostPortProfileServiceHostPortProfileState) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeContainerHostPortProfileServiceHostPortProfileState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
