package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesVolumesISCSIVolumeSource com vmware admiral compute kubernetes entities volumes i s c s i volume source
// swagger:model com:vmware:admiral:compute:kubernetes:entities:volumes:ISCSIVolumeSource
type ComVmwareAdmiralComputeKubernetesEntitiesVolumesISCSIVolumeSource struct {

	// fs type
	FsType string `json:"fsType,omitempty"`

	// iqn
	Iqn string `json:"iqn,omitempty"`

	// iscsi interface
	IscsiInterface string `json:"iscsiInterface,omitempty"`

	// lun
	Lun int64 `json:"lun,omitempty"`

	// read only
	ReadOnly bool `json:"readOnly,omitempty"`

	// target portal
	TargetPortal string `json:"targetPortal,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities volumes i s c s i volume source
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesISCSIVolumeSource) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesISCSIVolumeSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesVolumesISCSIVolumeSource) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesVolumesISCSIVolumeSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
