package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesServiceKubernetesDescriptionServiceKubernetesDescription com vmware admiral compute kubernetes service kubernetes description service kubernetes description
// swagger:model com:vmware:admiral:compute:kubernetes:service:KubernetesDescriptionService:KubernetesDescription
type ComVmwareAdmiralComputeKubernetesServiceKubernetesDescriptionServiceKubernetesDescription struct {

	// creation time micros
	CreationTimeMicros int64 `json:"creationTimeMicros,omitempty"`

	// custom properties
	CustomProperties map[string]string `json:"customProperties,omitempty"`

	// desc
	Desc string `json:"desc,omitempty"`

	// group links
	GroupLinks []string `json:"groupLinks"`

	// id
	ID string `json:"id,omitempty"`

	// Serialized kubernetes entity in YAML format.
	KubernetesEntity string `json:"kubernetesEntity,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// region Id
	RegionID string `json:"regionId,omitempty"`

	// tag links
	TagLinks []string `json:"tagLinks"`

	// tenant links
	TenantLinks []string `json:"tenantLinks"`

	// The type of the kubernetes entity.
	Type string `json:"type,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes service kubernetes description service kubernetes description
func (m *ComVmwareAdmiralComputeKubernetesServiceKubernetesDescriptionServiceKubernetesDescription) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroupLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTagLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTenantLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesServiceKubernetesDescriptionServiceKubernetesDescription) validateGroupLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.GroupLinks) { // not required
		return nil
	}

	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesServiceKubernetesDescriptionServiceKubernetesDescription) validateTagLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TagLinks) { // not required
		return nil
	}

	return nil
}

func (m *ComVmwareAdmiralComputeKubernetesServiceKubernetesDescriptionServiceKubernetesDescription) validateTenantLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantLinks) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesServiceKubernetesDescriptionServiceKubernetesDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesServiceKubernetesDescriptionServiceKubernetesDescription) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesServiceKubernetesDescriptionServiceKubernetesDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
