package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeContainerMaintenanceContainerStats com vmware admiral compute container maintenance container stats
// swagger:model com:vmware:admiral:compute:container:maintenance:ContainerStats
type ComVmwareAdmiralComputeContainerMaintenanceContainerStats struct {

	// container stopped
	ContainerStopped bool `json:"containerStopped,omitempty"`

	// cpu usage
	CPUUsage float64 `json:"cpuUsage,omitempty"`

	// health check success
	HealthCheckSuccess bool `json:"healthCheckSuccess,omitempty"`

	// health failure count
	HealthFailureCount int64 `json:"healthFailureCount,omitempty"`

	// health success count
	HealthSuccessCount int64 `json:"healthSuccessCount,omitempty"`

	// mem limit
	MemLimit int64 `json:"memLimit,omitempty"`

	// mem usage
	MemUsage int64 `json:"memUsage,omitempty"`

	// network in
	NetworkIn int64 `json:"networkIn,omitempty"`

	// network out
	NetworkOut int64 `json:"networkOut,omitempty"`
}

// Validate validates this com vmware admiral compute container maintenance container stats
func (m *ComVmwareAdmiralComputeContainerMaintenanceContainerStats) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContainerMaintenanceContainerStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContainerMaintenanceContainerStats) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeContainerMaintenanceContainerStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
