package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription com vmware admiral compute container network container network description service container network description
// swagger:model com:vmware:admiral:compute:container:network:ContainerNetworkDescriptionService:ContainerNetworkDescription
type ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription struct {

	// creation time micros
	CreationTimeMicros int64 `json:"creationTimeMicros,omitempty"`

	// custom properties
	CustomProperties map[string]string `json:"customProperties,omitempty"`

	// desc
	Desc string `json:"desc,omitempty"`

	// The name of the driver for this network. Can be bridge, host, overlay, none.
	Driver string `json:"driver,omitempty"`

	// Composite Template use only. If set to true, specifies that this network exists outside of the Composite Template.
	External bool `json:"external,omitempty"`

	// Composite Template use only. The name of the external network. If set then the value of the attribute 'external' is considered 'true'.
	ExternalName string `json:"externalName,omitempty"`

	// group links
	GroupLinks []string `json:"groupLinks"`

	// id
	ID string `json:"id,omitempty"`

	// Instance Adapter reference for provisioning of containers.
	InstanceAdapterReference strfmt.URI `json:"instanceAdapterReference,omitempty"`

	// An IPAM configuration for a given network.
	IPAM *ComVmwareAdmiralComputeContainerNetworkIPAM `json:"ipam,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// A map of field-value pairs for a given network. These are usedto specify network options that are used by the network drivers.
	Options map[string]string `json:"options,omitempty"`

	// Link to the parent network description.
	ParentDescriptionLink string `json:"parentDescriptionLink,omitempty"`

	// region Id
	RegionID string `json:"regionId,omitempty"`

	// tag links
	TagLinks []string `json:"tagLinks"`

	// tenant links
	TenantLinks []string `json:"tenantLinks"`
}

// Validate validates this com vmware admiral compute container network container network description service container network description
func (m *ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroupLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIPAM(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTagLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTenantLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription) validateGroupLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.GroupLinks) { // not required
		return nil
	}

	return nil
}

func (m *ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription) validateIPAM(formats strfmt.Registry) error {

	if swag.IsZero(m.IPAM) { // not required
		return nil
	}

	if m.IPAM != nil {

		if err := m.IPAM.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ipam")
			}
			return err
		}
	}

	return nil
}

func (m *ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription) validateTagLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TagLinks) { // not required
		return nil
	}

	return nil
}

func (m *ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription) validateTenantLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.TenantLinks) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeContainerNetworkContainerNetworkDescriptionServiceContainerNetworkDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
