package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComVmwareAdmiralComputeKubernetesEntitiesCommonObjectMeta com vmware admiral compute kubernetes entities common object meta
// swagger:model com:vmware:admiral:compute:kubernetes:entities:common:ObjectMeta
type ComVmwareAdmiralComputeKubernetesEntitiesCommonObjectMeta struct {

	// annotations
	Annotations map[string]string `json:"annotations,omitempty"`

	// cluster name
	ClusterName string `json:"clusterName,omitempty"`

	// creation timestamp
	CreationTimestamp string `json:"creationTimestamp,omitempty"`

	// generate name
	GenerateName string `json:"generateName,omitempty"`

	// labels
	Labels map[string]string `json:"labels,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// self link
	SelfLink string `json:"selfLink,omitempty"`

	// uid
	UID string `json:"uid,omitempty"`
}

// Validate validates this com vmware admiral compute kubernetes entities common object meta
func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonObjectMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonObjectMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComVmwareAdmiralComputeKubernetesEntitiesCommonObjectMeta) UnmarshalBinary(b []byte) error {
	var res ComVmwareAdmiralComputeKubernetesEntitiesCommonObjectMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
