package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// JavaUtilMap java util map
// swagger:model java:util:Map
type JavaUtilMap interface{}
