codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "31...80"

  status:
    project:
      cmd:
        enabled: true
        paths: "cmd"
        target: auto
      lib:
        enabled: true
        paths: "lib"
        target: auto
      pkg:
        enabled: true
        paths: "pkg"
        target: auto
    patch:
      cmd:
        enabled: true
        paths: "cmd"
        target: auto
      lib:
        enabled: true
        paths: "lib"
        target: auto
      pkg:
        enabled: true
        paths: "pkg"
        target: auto
    changes:
      default: off

  ignore:
    - "tests/.*"
    - "vendor/.*"
    - "bin/.*"
    - "doc/.*"
    - "demos/.*"
    - "infra/.*"
    - "isos/.*"

  notify:
    slack:
      default:
        url: secret:4pFXYokWG94wD+p6Ik8TOyoGCMjIt1oC64dJI6bfN3NRSq9ON/VplYzuANYGq5DotCsxx+VOCbnshdKATbRUmRysanEs3C2E9FWk2+pOa7OEygT3QRoiYZJXLSGl77Ki5fPWx/cUlvfcJPDGGpvKB+zl007cqOgFSU26qZqff+w=
        threshold: 1%
        only_pulls: false
        branches: master
        flags: null
        paths: null

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
