# After any change to this file you MUST regenerate and checkin
# a .drone.sec even if no secrets were changed. The secrets file is tied
# to a specific .drone.yml so artifacts will not be uploaded to Bintray
# in following builds without an updated .drone.sec
---
clone:
  path: github.com/vmware/vic
  tags: true

build:
  components:
    image: golang:1.6.2
    pull: true
    environment:
      BIN: bin
      SHELL: /bin/bash
      VIC_ESX_TEST_URL: $$VIC_ESX_TEST_URL
    commands:
      - apt-get update
      - apt-get install -yq time
      - make components
      - make vic-machine

  iso-base:
    image: golang:1.6.2
    pull: true
    environment:
      BIN: bin
    commands:
      - apt-get update
      - apt-get install -yq time
      - make iso-base

  appliance-staging:
    image: golang:1.6.2
    pull: true
    environment:
      BIN: bin
    commands:
      - apt-get update
      - apt-get install -yq time
      - make appliance-staging

  appliance:
    image: golang:1.6.2
    pull: true
    environment:
      BIN: bin
      INIT: /lib/systemd/systemd
    commands:
      - apt-get update
      - apt-get install -yq time
      - make appliance

  bootstrap-staging:
    image: golang:1.6.2
    pull: true
    environment:
      BIN: bin
    commands:
      - apt-get update
      - apt-get install -yq time
      - make bootstrap-staging

  bootstrap:
    image: golang:1.6.2
    pull: true
    environment:
      BIN: bin
      INIT: /sbin/init
    commands:
      - apt-get update
      - apt-get install -yq time
      - make bootstrap

  test:
    image: golang:1.6.2
    pull: true
    environment:
      BIN: bin
      GOPATH: /drone
      SHELL: /bin/bash
      DOCKER_API_VERSION: "1.21"
      VIC_ESX_TEST_URL: $$VIC_ESX_TEST_URL
    commands:
      - apt-get update
      - apt-get install -yq time
      - make test
    when:
      success: true

  bundle:
    image: golang:1.6.2
    pull: true
    environment:
      BIN: bin
      BIN_TEMP_DIR: bin/vic
      GOPATH: /drone
      SHELL: /bin/bash
    commands:
      - apt-get update
      - apt-get install -yq time
      - rm -rf $BIN_TEMP_DIR
      - mkdir $BIN_TEMP_DIR
      - cp LICENSE $BIN_TEMP_DIR
      - cp doc/bundle/README $BIN_TEMP_DIR
      - cp $BIN/vic-machine* $BIN_TEMP_DIR
      - cp $BIN/appliance.iso $BIN_TEMP_DIR
      - cp $BIN/bootstrap.iso $BIN_TEMP_DIR
      - tar czvf $BIN/vic_$$BUILD_NUMBER.tar.gz -C $BIN vic
      - shasum -a 256 $BIN/vic_$$BUILD_NUMBER.tar.gz
    when:
      success: true

notify:
  slack:
    channel: vic-bots
    webhook_url: $$SLACK_URL
    username: drone
    when:
      repo: vmware/vic
      branch: master

publish:
  coverage:
    server: https://coverage.vmware.run
    token: $$GITHUB_AUTOMATION_API_KEY
    when:
      repo: vmware/vic
      branch: master
      success: true
  bintray:
    username: $$BINTRAY_USERNAME
    api_key: $$BINTRAY_API_KEY
    artifacts:
      - file: bin/vic_$$BUILD_NUMBER.tar.gz
        owner: vmware
        type: executable
        repository: vic-repo
        package: build
        version: $$BUILD_NUMBER
        target: vic_$$BUILD_NUMBER.tar.gz
        publish: true
    when:
      repo: vmware/vic
      branch: master
      success: true

cache:
  mount:
    - /drone/bin
    - bin

