# After any change to this file you MUST regenerate and checkin
# a .drone.sec even if no secrets were changed. The secrets file is tied
# to a specific .drone.yml so artifacts will not be uploaded to Bintray
# in following builds without an updated .drone.sec
---
clone:
  path: github.com/vmware/vic
  tags: true

build:
  components:
    image: golang:1.6.0
    pull: true
    environment:
      BIN: bin
      SHELL: /bin/bash
    commands:
      - make components
      - make install

  iso-base:
    image: golang:1.6.0
    pull: true
    environment:
      BIN: bin
    commands:
      - make iso-base 

  appliance-staging:
    image: golang:1.6.0
    pull: true
    environment:
      BIN: bin
    commands:
      - make appliance-staging

  appliance:
    image: golang:1.6.0
    pull: true
    environment:
      BIN: bin
      INIT: /lib/systemd/systemd
    commands:
      - make appliance

  test:
    image: golang:1.6.0
    pull: true
    environment:
      BIN: bin
      GOPATH: /drone
      SHELL: /bin/bash
      DOCKER_API_VERSION: "1.21"
      VIC_ESX_TEST_URL: $$VIC_ESX_TEST_URL
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    commands:
      - wget -q https://get.docker.com/builds/Linux/x86_64/docker-latest
      - chmod +x docker-latest
      - mv docker-latest /usr/local/bin/docker
      - make test
      - make integration-tests
    when:
      success: true

  bundle:
    image: golang:1.6.0
    pull: true
    environment:
      BIN: bin
      GOPATH: /drone
      SHELL: /bin/bash
    commands:
      - tar -cvf $BIN/vic_$$BUILD_NUMBER.tar.gz $BIN/appliance.iso $BIN/install.sh 
    when:
      success: true

publish:
  coverage:
    server: https://coverage.vmware.run
    token: $$GITHUB_AUTOMATION_API_KEY
    when:
      repo: vmware/vic
      branch: master
      success: true
  bintray:
    username: $$BINTRAY_USERNAME
    api_key: $$BINTRAY_API_KEY
    artifacts:
      - file: vic_$$BUILD_NUMBER.tar.gz
        owner: vmware
        type: executable
        repository: vic-repo
        package: build
        version: 0.1
        target: vic_$$BUILD_NUMBER.tar.gz
        publish: true
    when:
      repo: vmware/vic
      branch: master
      success: true

cache:
  mount:
    - /drone/bin
    - bin

