# After any change to this file you MUST regenerate and checkin
# a .drone-e2e.sec even if no secrets were changed.
---
clone:
  path: github.com/vmware/vic
  tags: true

build:
  all:
    image: vmware-docker-ci-repo.bintray.io/integration/vic-test:latest
    pull: true
    environment:
      BIN: bin
    commands:
      - make all

  test:
    image: vmware-docker-ci-repo.bintray.io/integration/vic-test:latest
    pull: true
    environment:
      BIN: bin
      GOPATH: /drone
      SHELL: /bin/bash
      DOCKER_API_VERSION: "1.21"
      VIC_ESX_TEST_URL: $$VIC_ESX_TEST_URL
    commands:
      - make test
    when:
      success: true

  integration-test:
    image: vmware-docker-ci-repo.bintray.io/integration/vic-test:latest
    pull: true
    environment:
      BIN: bin
      DOCKER_API_VERSION: "1.21"
      GOPATH: /drone
      LOG_TEMP_DIR: install-logs
      SHELL: /bin/bash
      VIC_ESX_TEST_URL: $$VIC_ESX_TEST_URL
      TEST_URL:  $$TEST_URL
      TEST_USERNAME:  $$TEST_USERNAME
      TEST_PASSWORD:  $$TEST_PASSWORD
      TEST_RESOURCE:  $$TEST_RESOURCE
      GOVC_URL:  $$TEST_USERNAME:$$TEST_PASSWORD@$$TEST_URL
      GOVC_INSECURE: true
      GOVC_USERNAME:  $$TEST_USERNAME
      GOVC_PASSWORD:  $$TEST_PASSWORD
      GOVC_RESOURCE_POOL:  $$TEST_RESOURCE
      GS_PROJECT_ID: $$GS_PROJECT_ID
      GS_CLIENT_EMAIL: $$GS_CLIENT_EMAIL
      GS_PRIVATE_KEY: $$GS_PRIVATE_KEY
    commands:
      - scripts/integration-test.sh
    when:
      success: true

  bundle:
    image: vmware-docker-ci-repo.bintray.io/integration/vic-test:latest
    pull: true
    environment:
      BIN: bin
      BIN_TEMP_DIR: bin/vic
      GOPATH: /drone
      SHELL: /bin/bash
    commands:
      - rm -rf $BIN_TEMP_DIR
      - mkdir $BIN_TEMP_DIR
      - cp LICENSE $BIN_TEMP_DIR
      - cp doc/bundle/README $BIN_TEMP_DIR
      - cp $BIN/vic-machine* $BIN_TEMP_DIR
      - cp $BIN/appliance.iso $BIN_TEMP_DIR
      - cp $BIN/bootstrap.iso $BIN_TEMP_DIR
      - tar czvf $BIN/vic_$$BUILD_NUMBER.tar.gz -C $BIN vic
      - shasum -a 256 $BIN/vic_$$BUILD_NUMBER.tar.gz
    when:
      success: true

publish:
  coverage:
    server: https://coverage.vmware.run
    token: $$GITHUB_AUTOMATION_API_KEY
    when:
      repo: vmware/vic
      branch: master
      success: true

  bintray:
    username: $$BINTRAY_USERNAME
    api_key: $$BINTRAY_API_KEY
    artifacts:
      - file: bin/vic_$$BUILD_NUMBER.tar.gz
        owner: vmware
        type: executable
        repository: vic-repo
        package: build
        version: $$BUILD_NUMBER
        target: vic_$$BUILD_NUMBER.tar.gz
        publish: true
    when:
      repo: vmware/vic
      branch: master
      success: true

cache:
  mount:
    - /drone/bin
    - bin
