
workspace:

  base: /go
  path: src/github.com/vmware/vic

pipeline:

  vic-integration-test-on-pr:
    image: 'wdc-harbor-ci.eng.vmware.com/default-project/vic-integration-test:1.44'
    pull: true
    privileged: true
    environment:
      BIN: bin
      GOPATH: /go
      SHELL: /bin/bash
      LOG_TEMP_DIR: install-logs
    secrets:
      - bridge_network
      - ci_domain
      - debug_vch
      - drone_server
      - drone_token
      - drone_machine
      - github_automation_api_key
      - gs_client_email
      - gs_private_key
      - gs_project_id
      - public_network
      - registry_password
      - reporting_server_url
      - syslog_passwd
      - syslog_server
      - syslog_user
      - test_datastore
      - test_resource
      - test_timeout
      - test_password
      - test_url_array
      - test_username
    commands:
      - 'export GOVC_INSECURE=true'
      - export GOVC_USERNAME=$TEST_USERNAME
      - echo $GOVC_USERNAME
      - 'export GOVC_PASSWORD=$${TEST_PASSWORD}'
      - 'export GOVC_DATASTORE=$${TEST_DATASTORE}'
      - export DOMAIN=$CI_DOMAIN
      - echo $DOMAIN
    volumes:
      - /tmp
    when:
      status: success

  notify-slack-on-pass:
    image: plugins/slack
    secrets:
      - slack_url
    webhook: $SLACK_URL
    username: drone
    template: "Testing, ignore pls"
