version: 2
group_defaults:
  required: 1
  author_approval:
    auto: true
  approve_by_comment:
    enabled: true
    approve_regex: 'Approved|:shipit:|:sheep::it:|:\+1:|LGTM|lgtm'
  reset_on_push:
    enabled: false

groups:
  tether:
    users:
      - caglar10ur
    conditions:
      files:
        includes:
          - "cmd/tether/*"
          - "lib/tether/*"

  build-ci-infra:
    users:
      - mhagen-vmware
    conditions:
      files:
        includes:
          - "demos/*"
          - "infra/*"
          - "tests/*"

  design-docs:
    users:
      - hickeng
    conditions:
      files:
        includes:
          - "doc/design/*"

  docs:
    users:
      - stuclem
    conditions:
      files:
        includes:
          - "doc/*"
        excludes:
          - "doc/design/*"

  nightlies:
    users:
      - rajanashok
    conditions:
      files:
        includes:
          - "tests/nightly/*"

  vcsim:
    users:
      - dougm
    conditions:
      files:
        includes:
          - "cmd/toolbox/*"
          - "cmd/vcsim/*"
          - "pkg/vsphere/simulator/*"
          - "pkg/vsphere/toolbox/*"

  docker-persona:
    users:
      - sflxn
    conditions:
      files:
        includes:
          - "lib/apiservers/engine/*"
          - "cmd/docker/*"
        excludes:
          - "lib/apiservers/portlayer/*"

  install:
    users:
      - emlin
    conditions:
      files:
        includes:
          - "cmd/vic-machine/*"
          - "lib/install/*"

  vicadmin:
    users:
      - jzt
    conditions:
      files:
        includes:
          - "cmd/vicadmin/*"
          - "lib/vicadmin/*"
          - "isos/vicadmin/*"

  port-layer-exec-interaction:
    users:
      - caglar10ur
    conditions:
      files:
        includes:
          - "lib/portlayer/attach/*"
          - "lib/portlayer/exec/*"
          - "lib/portlayer/exec2/*"

  port-layer-storage:
    users:
      - fdawg4l
    conditions:
      files:
        includes:
          - "lib/portlayer/storage/*"

  port-layer-store:
    users:
      - cgtexmex
    conditions:
      files:
        includes:
          - "lib/portlayer/store/*"


  port-layer-network:
    users:
      - hmahmood
    conditions:
      files:
        includes:
          - "cmd/vic-dns/*"
          - "lib/dns/*"
          - "lib/dhcp/*"
          - "lib/portlayer/network/*"

  events:
    users:
      - cgtexmex
    conditions:
      files:
        includes:
          - "lib/portlayer/event/*"

  imagec:
    users:
      - jzt
    conditions:
      files:
        includes:
          - "lib/imagec/*"

  vendor:
    users:
      - mdubya66
    conditions:
      files:
        includes:
          - "vendor/*"
  ui:
    users:
      - jooskim
    conditions:
      files:
        includes:
          - "ui/*"

  ui-cmd:
    users:
      - andrewtchin
    conditions:
      files:
        includes:
          - "cmd/vic-ui/*"
