version: 2
group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(Approved|:shipit:|:sheep::it:|:\+1:|LGTM)'
  reset_on_push:
    enabled: false
groups:
  test:
    required: 1
    users:
      - anchal-agrawal
    conditions:
           files:
             include:
               - '*.*'
        
