version: 2
group_defaults:
  required: 1
  author_approval:
    auto: true
  approve_by_comment:
    enabled: true
    approve_regex: 'Approved|:shipit:|:sheep::it:|:\+1:|LGTM|lgtm'
  reset_on_push:
    enabled: false

groups:
  contributors:
    required: 1
    teams:
      - feature-maintainers

  wolfpack:
    users:
      - nloc
      - lcastellano
    conditions:
      files:
        include:
          - "*"
