version: 2
group_defaults:
  required: 1
  author_approval:
    auto: true
  approve_by_comment:
    enabled: true
    approve_regex: 'Approved|:shipit:|:sheep::it:|:\+1:|LGTM|lgtm'
  reset_on_push:
    enabled: false

groups:
  contributors:
    required: 2
    users: all

  tether:
    users:
      - caglar10ur
      - hickeng
    conditions:
      files:
        include:
          - "cmd/tether/*"
          - "lib/tether/*"

  build-ci-infra:
    users:
      - mhagen-vmware
      - rajanashok
    conditions:
      files:
        include:
          - "demos/*"
          - "infra/*"
          - "tests/*"

  design-docs:
    users:
      - hickeng
    conditions:
      files:
        include:
          - "doc/design/*"

  docs:
    users:
      - stuclem
      - mdubya66
    conditions:
      files:
        include:
          - "doc/*"
        exclude:
          - "doc/design/*"
          - "doc/bundle/*"

  nightlies:
    users:
      - rajanashok
      - mhagen-vmware
    conditions:
      files:
        include:
          - "tests/nightly/*"

  log:
    users:
      - hmahmood
      - fdawg4l
    conditions:
      files:
        include:
          - "pkg/log/*"

  vcsim:
    users:
      - dougm
      - caglar10ur
    conditions:
      files:
        include:
          - "cmd/vcsim/*"
          - "pkg/vsphere/simulator/*"

  toolbox:
    users:
      - dougm
      - caglar10ur
    conditions:
      files:
        include:
          - "cmd/toolbox/*"
          - "pkg/vsphere/toolbox/*"

  unified-installer:
    users:
      - frapposelli
      - andrewtchin
    conditions:
      files:
        include:
          - "installer/*"

  docker-persona:
    users:
      - sflxn
      - cgtexmex
      - jzt
    conditions:
      files:
        include:
          - "lib/apiservers/engine/*"
          - "cmd/docker/*"
        exclude:
          - "lib/apiservers/portlayer/*"

  install:
    users:
      - emlin
      - andrewtchin
    conditions:
      files:
        include:
          - "cmd/vic-machine/*"
          - "lib/install/*"
  upgrade:
    users:
      - emlin
    conditions:
      files:
        include:
          - "lib/migration/*"

  config:
    users:
      - emlin
      - hickeng
    conditions:
      files:
        include:
          - "lib/config/*"
          - "lib/metadata/*"

  vicadmin:
    users:
      - jzt
      - gigawhitlocks
    conditions:
      files:
        include:
          - "cmd/vicadmin/*"
          - "lib/vicadmin/*"
          - "isos/vicadmin/*"

  port-layer-exec-interaction:
    users:
      - caglar10ur
      - hickeng
    conditions:
      files:
        include:
          - "lib/portlayer/attach/*"
          - "lib/portlayer/exec/*"
          - "lib/portlayer/exec2/*"

  port-layer-storage:
    users:
      - fdawg4l
    conditions:
      files:
        include:
          - "lib/portlayer/storage/*"

  port-layer-store:
    users:
      - cgtexmex
    conditions:
      files:
        include:
          - "lib/portlayer/store/*"


  package-kv-store:
    users:
      - fdawg4l
    conditions:
      files:
        include:
          - "pkg/kvstore/*"

  port-layer-network:
    users:
      - hmahmood
      - andrewtchin
      - caglar10ur
    conditions:
      files:
        include:
          - "cmd/vic-dns/*"
          - "lib/dns/*"
          - "lib/dhcp/*"
          - "lib/portlayer/network/*"

  events:
    users:
      - cgtexmex
    conditions:
      files:
        include:
          - "lib/portlayer/event/*"

  imagec:
    users:
      - jzt
    conditions:
      files:
        include:
          - "lib/imagec/*"

  vendor:
    users:
      - mdubya66
    conditions:
      files:
        include:
          - "vendor/*"
  ui:
    users:
      - jooskim
      - jak-atx
    conditions:
      files:
        include:
          - "ui/*"

  ui-cmd:
    users:
      - andrewtchin
    conditions:
      files:
        include:
          - "cmd/vic-ui/*"

  pullapprove:
    users:
      - gigawhitlocks
      - anchal-agrawal
    conditions:
      files:
        include:
          - ".pullapprove.yml"

  drone:
    users:
      - jakedsouza
      - rajanashok
      - mhagen-vmware
    conditions:
      files:
        include:
          - ".drone.yml"
          - ".drone.sec"
