#!/bin/sh
# Generate test coverage statistics for Go packages.
#
# Works around the fact that `go test -coverprofile` does not work
# with multiple packages, see https://code.google.com/p/go/issues/detail?id=6909
#
# Usage: script/coverage [--html]
#
#     --html        Create HTML report and open it in browser
#

set -e

workdir=.cover
profile="$workdir/cover.out"
mode=count

generate_cover_data() {
    rm -rf "$workdir"
    mkdir "$workdir"
    echo "Generating coverage report for: $@"
    for dir in $@; do
      pkgs=$(go list $dir/... | grep -v /vendor/)
      for pkg in $pkgs; do
          f="$workdir/$(echo $pkg | tr / -).cover"
          go test -v -covermode="$mode" -coverprofile="$f" "$pkg"
      done
    done

    echo "mode: $mode" >"$profile"
    grep -h -v "^mode:" $workdir/*.cover >>"$profile"
}

show_cover_report() {
    go tool cover -${1}="$profile"
}

TEST_DIRS=$@
generate_cover_data $TEST_DIRS
show_cover_report func
