# Copyright 2016 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.6.2

# update the underlying OS and install jq
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -yq jq

# build imagec and port-layer-server
ADD ./ $GOPATH/src/github.com/vmware/vic
RUN make -C $GOPATH/src/github.com/vmware/vic imagec portlayerapi

# download and install bats and helpers
RUN git clone https://github.com/sstephenson/bats /tmp/bats && \
        git clone https://github.com/ztombol/bats-assert $GOPATH/src/github.com/vmware/vic/tests/helpers/bats-assert && \
        git clone https://github.com/ztombol/bats-support $GOPATH/src/github.com/vmware/vic/tests/helpers/bats-support && \
        /tmp/bats/install.sh /usr/local

# run the actual tests
WORKDIR $GOPATH/src/github.com/vmware/vic/tests/
CMD /usr/local/bin/bats -t .
