# Copyright 2016 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.6.0
RUN apt-get update -yq
RUN apt-get install -yq jq
RUN git clone https://github.com/sstephenson/bats /tmp/bats
RUN mkdir -p /go/src/github.com/vmware/vic/tests/helpers
WORKDIR /go/src/github.com/vmware/vic/tests/helpers
RUN git clone https://github.com/ztombol/bats-assert
RUN git clone https://github.com/ztombol/bats-support
WORKDIR /tmp/bats
RUN ./install.sh /usr/local
WORKDIR /go/src
RUN mkdir -p github.com/vmware/vic
ADD ./ github.com/vmware/vic
WORKDIR github.com/vmware/vic/tests
CMD /usr/local/bin/bats -t .
