package resources_compute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/config/dynamic/admiral/models"
)

// PatchResourcesComputeIDReader is a Reader for the PatchResourcesComputeID structure.
type PatchResourcesComputeIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchResourcesComputeIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPatchResourcesComputeIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewPatchResourcesComputeIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchResourcesComputeIDOK creates a PatchResourcesComputeIDOK with default headers values
func NewPatchResourcesComputeIDOK() *PatchResourcesComputeIDOK {
	return &PatchResourcesComputeIDOK{}
}

/*PatchResourcesComputeIDOK handles this case with default header values.

Success
*/
type PatchResourcesComputeIDOK struct {
	Payload *models.ComVmwarePhotonControllerModelResourcesComputeServiceComputeState
}

func (o *PatchResourcesComputeIDOK) Error() string {
	return fmt.Sprintf("[PATCH /resources/compute/{id}][%d] patchResourcesComputeIdOK  %+v", 200, o.Payload)
}

func (o *PatchResourcesComputeIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComVmwarePhotonControllerModelResourcesComputeServiceComputeState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchResourcesComputeIDNotFound creates a PatchResourcesComputeIDNotFound with default headers values
func NewPatchResourcesComputeIDNotFound() *PatchResourcesComputeIDNotFound {
	return &PatchResourcesComputeIDNotFound{}
}

/*PatchResourcesComputeIDNotFound handles this case with default header values.

Error
*/
type PatchResourcesComputeIDNotFound struct {
	Payload *models.ComVmwareXenonCommonServiceErrorResponse
}

func (o *PatchResourcesComputeIDNotFound) Error() string {
	return fmt.Sprintf("[PATCH /resources/compute/{id}][%d] patchResourcesComputeIdNotFound  %+v", 404, o.Payload)
}

func (o *PatchResourcesComputeIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComVmwareXenonCommonServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
