package resources_compute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/config/dynamic/admiral/models"
)

// PostResourcesComputeIDReader is a Reader for the PostResourcesComputeID structure.
type PostResourcesComputeIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostResourcesComputeIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostResourcesComputeIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewPostResourcesComputeIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostResourcesComputeIDOK creates a PostResourcesComputeIDOK with default headers values
func NewPostResourcesComputeIDOK() *PostResourcesComputeIDOK {
	return &PostResourcesComputeIDOK{}
}

/*PostResourcesComputeIDOK handles this case with default header values.

Success
*/
type PostResourcesComputeIDOK struct {
	Payload *models.ComVmwarePhotonControllerModelResourcesComputeServiceComputeState
}

func (o *PostResourcesComputeIDOK) Error() string {
	return fmt.Sprintf("[POST /resources/compute/{id}][%d] postResourcesComputeIdOK  %+v", 200, o.Payload)
}

func (o *PostResourcesComputeIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComVmwarePhotonControllerModelResourcesComputeServiceComputeState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostResourcesComputeIDNotFound creates a PostResourcesComputeIDNotFound with default headers values
func NewPostResourcesComputeIDNotFound() *PostResourcesComputeIDNotFound {
	return &PostResourcesComputeIDNotFound{}
}

/*PostResourcesComputeIDNotFound handles this case with default header values.

Error
*/
type PostResourcesComputeIDNotFound struct {
	Payload *models.ComVmwareXenonCommonServiceErrorResponse
}

func (o *PostResourcesComputeIDNotFound) Error() string {
	return fmt.Sprintf("[POST /resources/compute/{id}][%d] postResourcesComputeIdNotFound  %+v", 404, o.Payload)
}

func (o *PostResourcesComputeIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComVmwareXenonCommonServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
