package resources_compute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/config/dynamic/admiral/models"
)

// NewPostResourcesComputeIDParams creates a new PostResourcesComputeIDParams object
// with the default values initialized.
func NewPostResourcesComputeIDParams() *PostResourcesComputeIDParams {
	var ()
	return &PostResourcesComputeIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostResourcesComputeIDParamsWithTimeout creates a new PostResourcesComputeIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostResourcesComputeIDParamsWithTimeout(timeout time.Duration) *PostResourcesComputeIDParams {
	var ()
	return &PostResourcesComputeIDParams{

		timeout: timeout,
	}
}

// NewPostResourcesComputeIDParamsWithContext creates a new PostResourcesComputeIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostResourcesComputeIDParamsWithContext(ctx context.Context) *PostResourcesComputeIDParams {
	var ()
	return &PostResourcesComputeIDParams{

		Context: ctx,
	}
}

// NewPostResourcesComputeIDParamsWithHTTPClient creates a new PostResourcesComputeIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostResourcesComputeIDParamsWithHTTPClient(client *http.Client) *PostResourcesComputeIDParams {
	var ()
	return &PostResourcesComputeIDParams{
		HTTPClient: client,
	}
}

/*PostResourcesComputeIDParams contains all the parameters to send to the API endpoint
for the post resources compute ID operation typically these are written to a http.Request
*/
type PostResourcesComputeIDParams struct {

	/*Body*/
	Body models.ComVmwareXenonCommonServiceDocument
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post resources compute ID params
func (o *PostResourcesComputeIDParams) WithTimeout(timeout time.Duration) *PostResourcesComputeIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post resources compute ID params
func (o *PostResourcesComputeIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post resources compute ID params
func (o *PostResourcesComputeIDParams) WithContext(ctx context.Context) *PostResourcesComputeIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post resources compute ID params
func (o *PostResourcesComputeIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post resources compute ID params
func (o *PostResourcesComputeIDParams) WithHTTPClient(client *http.Client) *PostResourcesComputeIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post resources compute ID params
func (o *PostResourcesComputeIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post resources compute ID params
func (o *PostResourcesComputeIDParams) WithBody(body models.ComVmwareXenonCommonServiceDocument) *PostResourcesComputeIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post resources compute ID params
func (o *PostResourcesComputeIDParams) SetBody(body models.ComVmwareXenonCommonServiceDocument) {
	o.Body = body
}

// WithID adds the id to the post resources compute ID params
func (o *PostResourcesComputeIDParams) WithID(id string) *PostResourcesComputeIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post resources compute ID params
func (o *PostResourcesComputeIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostResourcesComputeIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
