#!/bin/bash

# This entry point gets invoked invoked for sysV init based
# bootstraps.
# It will load any custom prep for the repo in question, as
# defined in repos/name/init.sh then continue with the common
# bootstrap script

# path consistency
export PATH=$PATH:/sbin

# load the customizations
echo Loading repo customizations
. /bin/repoinit

# make some of the basics and start udev
mknod -m 622 /dev/console c 5 1
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/ptmx c 5 2
mknod -m 666 /dev/tty c 5 0
mknod -m 444 /dev/random c 1 8
mknod -m 444 /dev/urandom c 1 9
chown root:tty /dev/{console,ptmx,tty}

mkdir -p /dev/{pts,shm}
mount -t devpts -o gid=4,mode=620 none /dev/pts
mount -t tmpfs none /dev/shm

udevd --daemon
udevadm trigger

# we seem to need a second trigger to get full population
# this is done in the bootstrap after module load

# launch the main entry point
. /bin/bootstrap