package com.vmware.suitaf.apl;

public enum Key {

    ALT ("Alt (left-side Alt key)"),
    APPLICATION ("Application (open context menu on the last active control)"),
	BACKSPACE ("Backspace (backspace key)"),
    BREAK ("Break (Ctrl-Break)"),
    CANCEL ("Cancel (break)"),
    CAPSLOCK ("CapsLock (toggle whether it is currently on or off)"),
    CLEAR ("Clear (Clear key)"),
    CTRL ("Ctrl (Left-side Ctrl key)"),
    DELETE ("Delete (Delete key)"),
    DOWN ("Down (Down arrow)"),
    END ("End (End key)"),
    ENTER ("Enter (Enter key)"),
    ESC ("Esc (Escape)"),
    EXECUTE ("Execute (Execute key)"),
    F1 ("F1 (F1 function key)"),
    F2 ("F2 (F2 function key)"),
    F3 ("F3 (F3 function key)"),
    F4 ("F4 (F4 function key)"),
    F5 ("F5 (F5 function key)"),
    F6 ("F6 (F6 function key)"),
    F7 ("F7 (F7 function key)"),
    F8 ("F8 (F8 function key)"),
    F9 ("F9 (F9 function key)"),
    F10 ("F10 (F10 function key)"),
    F11 ("F11 (F11 function key)"),
    F12 ("F12 (F12 function key)"),
    GREATER_THAN ("Greater Than '>' key"),
    HELP ("Help (Help key)"),
    HOME ("Home (Home key)"),
    INSERT ("Insert (Insert key)"),
    LEFT ("Left (Left arrow)"),
    LEFT_ALT ("Left Alt (Alt key)"),
    LEFT_CTRL ("Left Ctrl (Ctrl key)"),
    LEFT_SHIFT ("Left Shift (Shift key)"),
    LEFT_WIN ("LeftWin (Windows Start menu key)"),
    LESS_THAN ("Less Than '<' key"),
    MENU ("Menu (Menu key)"),
    MODE ("Mode (Mode key)"),
    PAUSE ("Pause (Pause)"),
    PGDN ("PgDn (PgDn or Page Down)"),
    PGUP ("PgUp (PgUp or Page Up)"),
    PRTSCR ("PrtScr (Print Scrn)"),
    REDO ("Redo (Redo key)"),
    RIGHT ("Right (Right arrow)"),
    RIGHT_ALT ("Right Alt (Alt key)"),
    RIGHT_CTRL ("Right Ctrl (Ctrl key)"),
    RIGHT_OPTION ("RightOption (Option key)"),
    RIGHT_SHIFT ("Right Shift (Shift key)"),
    RIGHT_WIN ("RightWin (Windows Start menu key)"),
    SCROLL_LOCK ("ScrollLock (typed whether it is currently on or off)"),
    SHIFT ("Shift (Left-side Shift key)"),
    SPACE ("Space (Space bar)"),
    TAB ("Tab (Tab)"),
    UNDO ("Undo (Undo key)"),
    UP ("Up (Up arrow)"),
    ;

    public final String description;
    private Key(String description) {
        this.description = description;
    }
}
