package config_registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetConfigRegistriesIDParams creates a new GetConfigRegistriesIDParams object
// with the default values initialized.
func NewGetConfigRegistriesIDParams() *GetConfigRegistriesIDParams {
	var ()
	return &GetConfigRegistriesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetConfigRegistriesIDParamsWithTimeout creates a new GetConfigRegistriesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetConfigRegistriesIDParamsWithTimeout(timeout time.Duration) *GetConfigRegistriesIDParams {
	var ()
	return &GetConfigRegistriesIDParams{

		timeout: timeout,
	}
}

// NewGetConfigRegistriesIDParamsWithContext creates a new GetConfigRegistriesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetConfigRegistriesIDParamsWithContext(ctx context.Context) *GetConfigRegistriesIDParams {
	var ()
	return &GetConfigRegistriesIDParams{

		Context: ctx,
	}
}

// NewGetConfigRegistriesIDParamsWithHTTPClient creates a new GetConfigRegistriesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetConfigRegistriesIDParamsWithHTTPClient(client *http.Client) *GetConfigRegistriesIDParams {
	var ()
	return &GetConfigRegistriesIDParams{
		HTTPClient: client,
	}
}

/*GetConfigRegistriesIDParams contains all the parameters to send to the API endpoint
for the get config registries ID operation typically these are written to a http.Request
*/
type GetConfigRegistriesIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get config registries ID params
func (o *GetConfigRegistriesIDParams) WithTimeout(timeout time.Duration) *GetConfigRegistriesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get config registries ID params
func (o *GetConfigRegistriesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get config registries ID params
func (o *GetConfigRegistriesIDParams) WithContext(ctx context.Context) *GetConfigRegistriesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get config registries ID params
func (o *GetConfigRegistriesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get config registries ID params
func (o *GetConfigRegistriesIDParams) WithHTTPClient(client *http.Client) *GetConfigRegistriesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get config registries ID params
func (o *GetConfigRegistriesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get config registries ID params
func (o *GetConfigRegistriesIDParams) WithID(id string) *GetConfigRegistriesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get config registries ID params
func (o *GetConfigRegistriesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetConfigRegistriesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
