package config_registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/config/dynamic/admiral/models"
)

// NewPatchConfigRegistriesIDParams creates a new PatchConfigRegistriesIDParams object
// with the default values initialized.
func NewPatchConfigRegistriesIDParams() *PatchConfigRegistriesIDParams {
	var ()
	return &PatchConfigRegistriesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchConfigRegistriesIDParamsWithTimeout creates a new PatchConfigRegistriesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchConfigRegistriesIDParamsWithTimeout(timeout time.Duration) *PatchConfigRegistriesIDParams {
	var ()
	return &PatchConfigRegistriesIDParams{

		timeout: timeout,
	}
}

// NewPatchConfigRegistriesIDParamsWithContext creates a new PatchConfigRegistriesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchConfigRegistriesIDParamsWithContext(ctx context.Context) *PatchConfigRegistriesIDParams {
	var ()
	return &PatchConfigRegistriesIDParams{

		Context: ctx,
	}
}

// NewPatchConfigRegistriesIDParamsWithHTTPClient creates a new PatchConfigRegistriesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchConfigRegistriesIDParamsWithHTTPClient(client *http.Client) *PatchConfigRegistriesIDParams {
	var ()
	return &PatchConfigRegistriesIDParams{
		HTTPClient: client,
	}
}

/*PatchConfigRegistriesIDParams contains all the parameters to send to the API endpoint
for the patch config registries ID operation typically these are written to a http.Request
*/
type PatchConfigRegistriesIDParams struct {

	/*Body*/
	Body models.ComVmwareXenonCommonServiceDocument
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) WithTimeout(timeout time.Duration) *PatchConfigRegistriesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) WithContext(ctx context.Context) *PatchConfigRegistriesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) WithHTTPClient(client *http.Client) *PatchConfigRegistriesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) WithBody(body models.ComVmwareXenonCommonServiceDocument) *PatchConfigRegistriesIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) SetBody(body models.ComVmwareXenonCommonServiceDocument) {
	o.Body = body
}

// WithID adds the id to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) WithID(id string) *PatchConfigRegistriesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch config registries ID params
func (o *PatchConfigRegistriesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchConfigRegistriesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
