package config_registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/config/dynamic/admiral/models"
)

// NewPostConfigRegistriesParams creates a new PostConfigRegistriesParams object
// with the default values initialized.
func NewPostConfigRegistriesParams() *PostConfigRegistriesParams {
	var ()
	return &PostConfigRegistriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostConfigRegistriesParamsWithTimeout creates a new PostConfigRegistriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostConfigRegistriesParamsWithTimeout(timeout time.Duration) *PostConfigRegistriesParams {
	var ()
	return &PostConfigRegistriesParams{

		timeout: timeout,
	}
}

// NewPostConfigRegistriesParamsWithContext creates a new PostConfigRegistriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostConfigRegistriesParamsWithContext(ctx context.Context) *PostConfigRegistriesParams {
	var ()
	return &PostConfigRegistriesParams{

		Context: ctx,
	}
}

// NewPostConfigRegistriesParamsWithHTTPClient creates a new PostConfigRegistriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostConfigRegistriesParamsWithHTTPClient(client *http.Client) *PostConfigRegistriesParams {
	var ()
	return &PostConfigRegistriesParams{
		HTTPClient: client,
	}
}

/*PostConfigRegistriesParams contains all the parameters to send to the API endpoint
for the post config registries operation typically these are written to a http.Request
*/
type PostConfigRegistriesParams struct {

	/*Body*/
	Body *models.ComVmwareAdmiralServiceCommonRegistryServiceRegistryState

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post config registries params
func (o *PostConfigRegistriesParams) WithTimeout(timeout time.Duration) *PostConfigRegistriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post config registries params
func (o *PostConfigRegistriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post config registries params
func (o *PostConfigRegistriesParams) WithContext(ctx context.Context) *PostConfigRegistriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post config registries params
func (o *PostConfigRegistriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post config registries params
func (o *PostConfigRegistriesParams) WithHTTPClient(client *http.Client) *PostConfigRegistriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post config registries params
func (o *PostConfigRegistriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post config registries params
func (o *PostConfigRegistriesParams) WithBody(body *models.ComVmwareAdmiralServiceCommonRegistryServiceRegistryState) *PostConfigRegistriesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post config registries params
func (o *PostConfigRegistriesParams) SetBody(body *models.ComVmwareAdmiralServiceCommonRegistryServiceRegistryState) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostConfigRegistriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models.ComVmwareAdmiralServiceCommonRegistryServiceRegistryState)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
