# Copyright 2016 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: "2.0"
info:
  description: "Port Layer API"
  title: "Port Layer API"
  version: "v0.0.1"
produces:
- application/json
consumes:
- application/json
schemes:
- http
paths:
  /_ping:
    get:
      description: "Pings the server to see if it's running"
      summary: "ping the portlayer server"
      tags: ["misc"]
      operationId: Ping
      produces:
        - text/plain
      responses:
        '200':
          description: "OK"
          schema:
            type: string
  /storage:
    post:
      description: "Creates a location to store images"
      summary: "creates an image store"
      tags: ["storage"]
      operationId: CreateImageStore
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/ImageStore"
      responses:
        '201':
          description: "Created"
          schema:
            $ref: "#/definitions/StoreUrl"
        '409':
          description: "An image store with that name already exists."
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /storage/{store_name}:
    get:
      description: "Retrieves a list of images given a list of image IDs, or all images in the image store if no param is passed."
      summary: "Retrieve a list of images in an image store"
      tags: ["storage"]
      operationId: ListImages
      parameters:
        - name: store_name
          type: string
          in: path
          required: true
        - name: ids
          type: string
          in: query
          type: array
          items:
            type: string
            collectionFormat: csv
      responses:
        '200':
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Image"
        '404':
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "error"
          schema:
           $ref: "#/definitions/Error"
    post:
      description: "Creates a new image layer in an image store"
      summary: "Creates a new image layer"
      tags: ["storage"]
      operationId: WriteImage
      consumes:
        - application/octet-stream
      parameters:
        - name: image_file
          in: body
          schema:
            type: string
            format: binary
        - name: store_name
          type: string
          in: path
          required: true
        - name: image_id
          type: string
          in: query
          required: true
        - name: parent_id
          type: string
          in: query
          required: true
        - name: sum
          type: string
          in: query
          required: true
        - name: metadatakey
          type: string
          in: query
        - name: metadataval
          type: string
          in: query
      responses:
        '201':
          description: "Created"
          schema:
            $ref: "#/definitions/Image"
        default:
          description: "error"
          schema:
           $ref: "#/definitions/Error"
  /storage/{store_name}/info/{id}:
    get:
      description: "Inspect an image by id in an image store"
      summary: "Inspect an image"
      tags: ["storage"]
      operationId: GetImage
      parameters:
        - name: store_name
          type: string
          in: path
          required: true
        - name: id
          type: string
          in: path
          required: true
      responses:
        '404':
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        '200':
          description: "OK"
          schema:
            $ref: "#/definitions/Image"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /storage/{store_name}/tar/{id}:
    get:
      description: "Get an image by id in an image store as a tar file"
      summary: "Get an image as a tar file"
      tags: ["storage"]
      operationId: GetImageTar
      parameters:
        - name: store_name
          type: string
          in: path
          required: true
        - name: id
          type: string
          in: path
          required: true
      responses:
        '404':
          description: "Not found"
        '200':
          description: "OK"
          schema:
            type: string
            format: binary
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /scopes:
    post:
      summary: "Create a new scope"
      tags: ["scopes"]
      operationId: CreateScope
      parameters:
        - name: config
          in: body
          schema:
            $ref: "#/definitions/ScopeConfig"
      responses:
        '201':
          description: "Created"
          schema:
            $ref: "#/definitions/ScopeConfig"
        '409':
          description: "A scope with that name exists."
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
    get:
      tags: ["scopes"]
      operationId: ListAll
      responses:
        '200':
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/ScopeConfig"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /scopes/{idName}:
    get:
      tags: ["scopes"]
      operationId: List
      parameters:
        - name: idName
          type: string
          in: path
          required: true
      responses:
        '200':
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/ScopeConfig"
        '404':
          description: "Not found"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /scopes/containers/{handle}:
    post:
      description: "Add a container to scopes modifying the conatiner VM's config as necessary"
      tags: ["scopes"]
      operationId: AddContainer
      parameters:
        - name: handle
          required: true
          in: path
          type: string
        - name: networkConfig
          in: body
          schema:
            $ref: "#/definitions/NetworkConfig"
          required: true
      responses:
        '200':
          description: "OK"
          schema:
            type: string
        '404':
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /scopes/containers/{handle}/binding:
    post:
      tags: ["scopes"]
      description: "Perform scope initialization for each of the scopes the container belongs to. Network initialization may include, for example, assigning addresses on a scope."
      operationId: BindContainer
      consumes:
        - application/octet-stream
        - application/json
      produces:
        - application/json
      parameters:
        - name: handle
          required: true
          in: path
          type: string
      responses:
        '200':
          description: "OK"
          schema:
            type: string
        '404':
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags: ["scopes"]
      operationId: UnbindContainer
      consumes:
        - application/octet-stream
        - application/json
      produces:
        - application/json
      parameters:
        - name: handle
          required: true
          in: path
          type: string
      responses:
        '200':
          description: "OK"
          schema:
            type: string
        '404':
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "error"
          schema:
            $ref: "#/definitions/Error"
  /containers:
    post:
      description: "Initiates a container create operation"
      summary: "Initiates a container create operation"
      operationId: Create
      tags: ["containers"]
      consumes:
        - application/json
        - application/octet-stream
      produces:
        - application/json
      parameters:
        - name: name
          in: query
          type: string
          pattern: "/?[a-zA-Z0-9_-]+"
        - name: createConfig
          in: body
          required: true
          schema:
            $ref: "#/definitions/ContainerCreateConfig"
      responses:
        '404':
          description: "Create failed"
          schema:
            $ref: "#/definitions/Error"
        '200':
          description: "OK"
          schema:
            $ref: "#/definitions/ContainerCreatedInfo"
  /containers/{id}:
    get:
      description: "Get a container handle"
      operationId: Get
      tags: ["containers"]
      consumes:
        - application/json
        - application/octet-stream
      produces:
        - application/json
      parameters:
        - name: id
          required: true
          in: path
          type: string
      responses:
        '404':
          description: "not found"
        '200':
          description: "OK"
          schema:
            type: string
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/Error"
  /containers/{handle}:
    put:
      description: "Commit and close a container handle"
      operationId: Commit
      tags: ["containers"]
      consumes:
        - application/json
        - application/octet-stream
      produces:
        - application/json
      parameters:
        - name: handle
          in: path
          required: true
          type: string
      responses:
        '404':
          description: "not found"
        '200':
          description: "OK"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/Error"
  /containers/{handle}/state:
    put:
      description: "Changes the state of a container"
      operationId: StateChange
      tags: ["containers"]
      consumes:
        - application/octet-stream
        - application/json
      produces:
        - application/json
      parameters:
        - name: handle
          required: true
          in: path
          type: string
        - name: state
          required: true
          in: body
          schema:
            type: string
            enum: ["RUNNING", "STOPPED"]
      responses:
        '404':
          description: "not found"
          schema:
            $ref: "#/definitions/Error"
        '200':
          description: "OK"
          schema:
            type: string
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/Error"
  /interaction/{id}/join:
    post:
      description: "Establish an interaction session with a container by id"
      summary: "Establishes an interactive session (ala docker attach)"
      operationId: ContainerJoin
      tags: ["interaction"]
      consumes:
        - application/octet-stream
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          type: string
          required: true
      responses:
        '404':
          description: "Container not found"
          schema:
            $ref: "#/definitions/Error"
        '200':
          description: "OK"
definitions:
  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  StoreUrl:
    type: object
    required:
      - url
    properties:
      code:
        type: integer
        format: int64
      url:
        type: string
  ImageStore:
    type: object
    required:
      - name
    properties:
      name:
        type: string
  Image:
    type: object
    required:
      - ID
      - Store
    properties:
      ID:
        type: string
      SelfLink:
        type: string
      Parent:
        type: string
      Store:
        type: string
      Metadata:
        type: object
        additionalProperties:
                type: string
  ScopeConfig:
    type: object
    required:
      - name
      - scopeType
    properties:
      id:
        type: string
      name:
        type: string
      scopeType:
        type: string
      subnet:
        type: string
      gateway:
        type: string
      dns:
        type: array
        items:
          type: string
      ipam:
        type: array
        items:
          type: string
  ContainerCreateConfig:
    type: object
    properties:
      imageStore:
        $ref: "#/definitions/ImageStore"
      image:
        type: string
      path:
        type: string
      args:
        type: array
        items:
          type: string
      workingDir:
        type: string
      env:
        type: array
        items:
          type: string
      networkDisabled:
        type: boolean
      tty:
        type: boolean
        default: false
  ContainerCreatedInfo:
    type: object
    required:
      - handle
      - id
    properties:
      handle:
        type: string
      id:
        type: string
  NetworkConfig:
    type: object
    required:
      - networkName
    properties:
      networkName:
        type: string
      address:
        type: string
