#docker login
#docker build -t vic-test -f Dockerfile.test .
#docker tag vic-test vmware-docker-ci-repo.bintray.io/integration/vic-test:1.x
#docker push vmware-docker-ci-repo.bintray.io/integration/vic-test
FROM golang:1.7

RUN apt-get update
RUN apt-get install -y jq time
RUN curl -sSL https://get.docker.com/ | sh

RUN apt-get install -y gcc python-dev python-setuptools python-pip libffi-dev libssl-dev
RUN pip install pyasn1 gsutil --upgrade
RUN pip install robotframework
RUN pip install robotframework-sshlibrary

RUN curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-1.11.2.tgz && tar --strip-components=1 -xvzf docker-1.11.2.tgz -C /usr/local/bin

RUN curl -sSL https://github.com/vmware/govmomi/releases/download/v0.7.0/govc_linux_amd64.gz | gzip -d > /usr/local/bin/govc
RUN chmod +x /usr/local/bin/govc

RUN curl http://downloads.drone.io/drone-cli/drone_linux_amd64.tar.gz | tar zx
RUN install -t /usr/local/bin drone

Run apt-get install sshpass

Run apt-get install -yq ant openjdk-7-jdk

Run apt-get install unzip
Run apt-get install zip
