package kv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vmware/vic/lib/apiservers/portlayer/models"
)

/*PutValueOK OK

swagger:response putValueOK
*/
type PutValueOK struct {
}

// NewPutValueOK creates PutValueOK with default headers values
func NewPutValueOK() *PutValueOK {
	return &PutValueOK{}
}

// WriteResponse to the client
func (o *PutValueOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*PutValueInternalServerError error

swagger:response putValueInternalServerError
*/
type PutValueInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutValueInternalServerError creates PutValueInternalServerError with default headers values
func NewPutValueInternalServerError() *PutValueInternalServerError {
	return &PutValueInternalServerError{}
}

// WithPayload adds the payload to the put value internal server error response
func (o *PutValueInternalServerError) WithPayload(payload *models.Error) *PutValueInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put value internal server error response
func (o *PutValueInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutValueInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
