package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/apiservers/portlayer/models"
)

// NewCreateParams creates a new CreateParams object
// with the default values initialized.
func NewCreateParams() CreateParams {
	var ()
	return CreateParams{}
}

// CreateParams contains all the bound params for the create operation
// typically these are obtained from a http.Request
//
// swagger:parameters Create
type CreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: body
	*/
	CreateConfig *models.ContainerCreateConfig
	/*
	  Pattern: /?[a-zA-Z0-9_-]+
	  In: query
	*/
	Name *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ContainerCreateConfig
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("createConfig", "body"))
			} else {
				res = append(res, errors.NewParseError("createConfig", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.CreateConfig = &body
			}
		}

	} else {
		res = append(res, errors.Required("createConfig", "body"))
	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Name = &raw

	if err := o.validateName(formats); err != nil {
		return err
	}

	return nil
}

func (o *CreateParams) validateName(formats strfmt.Registry) error {

	if err := validate.Pattern("name", "query", (*o.Name), `/?[a-zA-Z0-9_-]+`); err != nil {
		return err
	}

	return nil
}
