package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetContainerLogsURL generates an URL for the get container logs operation
type GetContainerLogsURL struct {
	ID string

	Deadline  *int64
	Follow    *bool
	Since     *int64
	Taillines *int64
	Timestamp *bool

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetContainerLogsURL) WithBasePath(bp string) *GetContainerLogsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetContainerLogsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetContainerLogsURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/containers/{id}/logs"

	id := o.ID
	if id != "" {
		_path = strings.Replace(_path, "{id}", id, -1)
	} else {
		return nil, errors.New("ID is required on GetContainerLogsURL")
	}
	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var deadline string
	if o.Deadline != nil {
		deadline = swag.FormatInt64(*o.Deadline)
	}
	if deadline != "" {
		qs.Set("deadline", deadline)
	}

	var follow string
	if o.Follow != nil {
		follow = swag.FormatBool(*o.Follow)
	}
	if follow != "" {
		qs.Set("follow", follow)
	}

	var since string
	if o.Since != nil {
		since = swag.FormatInt64(*o.Since)
	}
	if since != "" {
		qs.Set("since", since)
	}

	var taillines string
	if o.Taillines != nil {
		taillines = swag.FormatInt64(*o.Taillines)
	}
	if taillines != "" {
		qs.Set("taillines", taillines)
	}

	var timestamp string
	if o.Timestamp != nil {
		timestamp = swag.FormatBool(*o.Timestamp)
	}
	if timestamp != "" {
		qs.Set("timestamp", timestamp)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetContainerLogsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetContainerLogsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetContainerLogsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetContainerLogsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetContainerLogsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetContainerLogsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
