package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetContainerStatsOK OK

swagger:response getContainerStatsOK
*/
type GetContainerStatsOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetContainerStatsOK creates GetContainerStatsOK with default headers values
func NewGetContainerStatsOK() *GetContainerStatsOK {
	return &GetContainerStatsOK{}
}

// WithPayload adds the payload to the get container stats o k response
func (o *GetContainerStatsOK) WithPayload(payload io.ReadCloser) *GetContainerStatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get container stats o k response
func (o *GetContainerStatsOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContainerStatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetContainerStatsNotFound Stats not found

swagger:response getContainerStatsNotFound
*/
type GetContainerStatsNotFound struct {
}

// NewGetContainerStatsNotFound creates GetContainerStatsNotFound with default headers values
func NewGetContainerStatsNotFound() *GetContainerStatsNotFound {
	return &GetContainerStatsNotFound{}
}

// WriteResponse to the client
func (o *GetContainerStatsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetContainerStatsInternalServerError Failed to get stats

swagger:response getContainerStatsInternalServerError
*/
type GetContainerStatsInternalServerError struct {
}

// NewGetContainerStatsInternalServerError creates GetContainerStatsInternalServerError with default headers values
func NewGetContainerStatsInternalServerError() *GetContainerStatsInternalServerError {
	return &GetContainerStatsInternalServerError{}
}

// WriteResponse to the client
func (o *GetContainerStatsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
