// Copyright 2017 VMware, Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.// Code generated by MockGen. DO NOT EDIT.
// Source: image.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	storage "github.com/vmware/vic/lib/apiservers/portlayer/client/storage"
	metadata "github.com/vmware/vic/lib/metadata"
)

// MockVicImageProxy is a mock of VicImageProxy interface
type MockVicImageProxy struct {
	ctrl     *gomock.Controller
	recorder *MockVicImageProxyMockRecorder
}

// MockVicImageProxyMockRecorder is the mock recorder for MockVicImageProxy
type MockVicImageProxyMockRecorder struct {
	mock *MockVicImageProxy
}

// NewMockVicImageProxy creates a new mock instance
func NewMockVicImageProxy(ctrl *gomock.Controller) *MockVicImageProxy {
	mock := &MockVicImageProxy{ctrl: ctrl}
	mock.recorder = &MockVicImageProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockVicImageProxy) EXPECT() *MockVicImageProxyMockRecorder {
	return m.recorder
}

// DeleteImage mocks base method
func (m *MockVicImageProxy) DeleteImage(ctx context.Context, storeName string, img *metadata.ImageConfig, keepNodes []string) (*storage.DeleteImageOK, error) {
	ret := m.ctrl.Call(m, "DeleteImage", ctx, storeName, img, keepNodes)
	ret0, _ := ret[0].(*storage.DeleteImageOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteImage indicates an expected call of DeleteImage
func (mr *MockVicImageProxyMockRecorder) DeleteImage(ctx, storeName, img, keepNodes interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockVicImageProxy)(nil).DeleteImage), ctx, storeName, img, keepNodes)
}
