FROM gcr.io/eminent-nation-87317/vic-integration-test:1.36
RUN mkdir -p /go/src/github.com/vmware/vic
COPY secrets /go/src/github.com/vmware/vic
ENV LONGEVITY=1
ENV GOVC_INSECURE=1
ENV GOVC_USERNAME=administrator@vsphere.local
ENV GOVC_DATASTORE=vsanDatastore
ENV TEST_DATASTORE=vsanDatastore
ENV TEST_USERNAME=administrator@vsphere.local
ENV TEST_TIMEOUT=3m
ENV TEST_RESOURCE=cls
ENV DOMAIN=
ENV BRIDGE_NETWORK=bridge
ENV EXTERNAL_NETWORK=vm-network
ENV DRONE_SERVER=http://ci.vmware.run
ENV DOCKER_API_VERSION=1.23
