# Copyright 2017-2018 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

FROM longevity-base
ENV GOVC_URL=10.146.13.19
ENV TEST_URL_ARRAY=10.146.13.19
ENV GOVC_DATASTORE=iSCSI-5TB-1
ENV TEST_DATASTORE=iSCSI-5TB-1
ENV BRIDGE_NETWORK=DVPortGroupVIC
ENV PUBLIC_NETWORK=VM Network
ENV TEST_DATACENTER=/Datacenter3
ENV STATIC_VCH_OPTIONS="--insecure-registry=vic-executor1.vcna.io --public-network-ip 10.197.37.66/23 --public-network-gateway 10.197.37.253 --dns-server 10.142.7.21"