FROM longevity-base
ENV GOVC_URL=blinky.eng.vmware.com
ENV TEST_URL_ARRAY=blinky.eng.vmware.com
ENV STATIC_VCH_OPTIONS="--public-network-ip 10.17.109.7/24 --public-network-gateway 10.17.109.253 --dns-server 10.118.81.1"
