package interaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vmware/vic/lib/apiservers/portlayer/models"
)

/*ContainerSetStdinOK OK

swagger:response containerSetStdinOK
*/
type ContainerSetStdinOK struct {
}

// NewContainerSetStdinOK creates ContainerSetStdinOK with default headers values
func NewContainerSetStdinOK() *ContainerSetStdinOK {
	return &ContainerSetStdinOK{}
}

// WriteResponse to the client
func (o *ContainerSetStdinOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*ContainerSetStdinNotFound Container not found

swagger:response containerSetStdinNotFound
*/
type ContainerSetStdinNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewContainerSetStdinNotFound creates ContainerSetStdinNotFound with default headers values
func NewContainerSetStdinNotFound() *ContainerSetStdinNotFound {
	return &ContainerSetStdinNotFound{}
}

// WithPayload adds the payload to the container set stdin not found response
func (o *ContainerSetStdinNotFound) WithPayload(payload *models.Error) *ContainerSetStdinNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container set stdin not found response
func (o *ContainerSetStdinNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerSetStdinNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ContainerSetStdinInternalServerError Failed to Set stdin

swagger:response containerSetStdinInternalServerError
*/
type ContainerSetStdinInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewContainerSetStdinInternalServerError creates ContainerSetStdinInternalServerError with default headers values
func NewContainerSetStdinInternalServerError() *ContainerSetStdinInternalServerError {
	return &ContainerSetStdinInternalServerError{}
}

// WithPayload adds the payload to the container set stdin internal server error response
func (o *ContainerSetStdinInternalServerError) WithPayload(payload *models.Error) *ContainerSetStdinInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the container set stdin internal server error response
func (o *ContainerSetStdinInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ContainerSetStdinInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
