package interaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ContainerResizeHandlerFunc turns a function with the right signature into a container resize handler
type ContainerResizeHandlerFunc func(ContainerResizeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ContainerResizeHandlerFunc) Handle(params ContainerResizeParams) middleware.Responder {
	return fn(params)
}

// ContainerResizeHandler interface for that can handle valid container resize params
type ContainerResizeHandler interface {
	Handle(ContainerResizeParams) middleware.Responder
}

// NewContainerResize creates a new http.Handler for the container resize operation
func NewContainerResize(ctx *middleware.Context, handler ContainerResizeHandler) *ContainerResize {
	return &ContainerResize{Context: ctx, Handler: handler}
}

/*ContainerResize swagger:route POST /interaction/{id}/resize interaction containerResize

Resize tty session

Resize the container's tty session

*/
type ContainerResize struct {
	Context *middleware.Context
	Handler ContainerResizeHandler
}

func (o *ContainerResize) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewContainerResizeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
