package interaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewContainerSetStdinParams creates a new ContainerSetStdinParams object
// with the default values initialized.
func NewContainerSetStdinParams() ContainerSetStdinParams {
	var ()
	return ContainerSetStdinParams{}
}

// ContainerSetStdinParams contains all the bound params for the container set stdin operation
// typically these are obtained from a http.Request
//
// swagger:parameters ContainerSetStdin
type ContainerSetStdinParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  In: query
	*/
	Deadline *strfmt.DateTime
	/*
	  Required: true
	  In: path
	*/
	ID string
	/*
	  In: body
	*/
	RawStream io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ContainerSetStdinParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDeadline, qhkDeadline, _ := qs.GetOK("deadline")
	if err := o.bindDeadline(qDeadline, qhkDeadline, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		o.RawStream = r.Body

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ContainerSetStdinParams) bindDeadline(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := formats.Parse("datetime", raw)
	if err != nil {
		return errors.InvalidType("deadline", "query", "strfmt.DateTime", raw)
	}
	o.Deadline = (value.(*strfmt.DateTime))

	return nil
}

func (o *ContainerSetStdinParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ID = raw

	return nil
}
