package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/config/dynamic/admiral/models"
)

// PostProjectsIDReader is a Reader for the PostProjectsID structure.
type PostProjectsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostProjectsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewPostProjectsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostProjectsIDOK creates a PostProjectsIDOK with default headers values
func NewPostProjectsIDOK() *PostProjectsIDOK {
	return &PostProjectsIDOK{}
}

/*PostProjectsIDOK handles this case with default header values.

Success
*/
type PostProjectsIDOK struct {
	Payload *models.ComVmwareAdmiralAuthProjectProjectServiceProjectState
}

func (o *PostProjectsIDOK) Error() string {
	return fmt.Sprintf("[POST /projects/{id}][%d] postProjectsIdOK  %+v", 200, o.Payload)
}

func (o *PostProjectsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComVmwareAdmiralAuthProjectProjectServiceProjectState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostProjectsIDNotFound creates a PostProjectsIDNotFound with default headers values
func NewPostProjectsIDNotFound() *PostProjectsIDNotFound {
	return &PostProjectsIDNotFound{}
}

/*PostProjectsIDNotFound handles this case with default header values.

Error
*/
type PostProjectsIDNotFound struct {
	Payload *models.ComVmwareXenonCommonServiceErrorResponse
}

func (o *PostProjectsIDNotFound) Error() string {
	return fmt.Sprintf("[POST /projects/{id}][%d] postProjectsIdNotFound  %+v", 404, o.Payload)
}

func (o *PostProjectsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComVmwareXenonCommonServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
