package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/config/dynamic/admiral/models"
)

// PostProjectsReader is a Reader for the PostProjects structure.
type PostProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostProjectsOK creates a PostProjectsOK with default headers values
func NewPostProjectsOK() *PostProjectsOK {
	return &PostProjectsOK{}
}

/*PostProjectsOK handles this case with default header values.

Success
*/
type PostProjectsOK struct {
	Payload *models.ComVmwareAdmiralAuthProjectProjectServiceProjectState
}

func (o *PostProjectsOK) Error() string {
	return fmt.Sprintf("[POST /projects][%d] postProjectsOK  %+v", 200, o.Payload)
}

func (o *PostProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComVmwareAdmiralAuthProjectProjectServiceProjectState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
