package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/config/dynamic/admiral/models"
)

// NewPutProjectsIDParams creates a new PutProjectsIDParams object
// with the default values initialized.
func NewPutProjectsIDParams() *PutProjectsIDParams {
	var ()
	return &PutProjectsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutProjectsIDParamsWithTimeout creates a new PutProjectsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutProjectsIDParamsWithTimeout(timeout time.Duration) *PutProjectsIDParams {
	var ()
	return &PutProjectsIDParams{

		timeout: timeout,
	}
}

// NewPutProjectsIDParamsWithContext creates a new PutProjectsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutProjectsIDParamsWithContext(ctx context.Context) *PutProjectsIDParams {
	var ()
	return &PutProjectsIDParams{

		Context: ctx,
	}
}

// NewPutProjectsIDParamsWithHTTPClient creates a new PutProjectsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutProjectsIDParamsWithHTTPClient(client *http.Client) *PutProjectsIDParams {
	var ()
	return &PutProjectsIDParams{
		HTTPClient: client,
	}
}

/*PutProjectsIDParams contains all the parameters to send to the API endpoint
for the put projects ID operation typically these are written to a http.Request
*/
type PutProjectsIDParams struct {

	/*Body*/
	Body models.ComVmwareXenonCommonServiceDocument
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put projects ID params
func (o *PutProjectsIDParams) WithTimeout(timeout time.Duration) *PutProjectsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put projects ID params
func (o *PutProjectsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put projects ID params
func (o *PutProjectsIDParams) WithContext(ctx context.Context) *PutProjectsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put projects ID params
func (o *PutProjectsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put projects ID params
func (o *PutProjectsIDParams) WithHTTPClient(client *http.Client) *PutProjectsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put projects ID params
func (o *PutProjectsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put projects ID params
func (o *PutProjectsIDParams) WithBody(body models.ComVmwareXenonCommonServiceDocument) *PutProjectsIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put projects ID params
func (o *PutProjectsIDParams) SetBody(body models.ComVmwareXenonCommonServiceDocument) {
	o.Body = body
}

// WithID adds the id to the put projects ID params
func (o *PutProjectsIDParams) WithID(id string) *PutProjectsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put projects ID params
func (o *PutProjectsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutProjectsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
