package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/vmware/vic/lib/config/dynamic/admiral/models"
)

// PutProjectsIDReader is a Reader for the PutProjectsID structure.
type PutProjectsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutProjectsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutProjectsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewPutProjectsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutProjectsIDOK creates a PutProjectsIDOK with default headers values
func NewPutProjectsIDOK() *PutProjectsIDOK {
	return &PutProjectsIDOK{}
}

/*PutProjectsIDOK handles this case with default header values.

Success
*/
type PutProjectsIDOK struct {
	Payload *models.ComVmwareAdmiralAuthProjectProjectServiceProjectState
}

func (o *PutProjectsIDOK) Error() string {
	return fmt.Sprintf("[PUT /projects/{id}][%d] putProjectsIdOK  %+v", 200, o.Payload)
}

func (o *PutProjectsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComVmwareAdmiralAuthProjectProjectServiceProjectState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutProjectsIDNotFound creates a PutProjectsIDNotFound with default headers values
func NewPutProjectsIDNotFound() *PutProjectsIDNotFound {
	return &PutProjectsIDNotFound{}
}

/*PutProjectsIDNotFound handles this case with default header values.

Error
*/
type PutProjectsIDNotFound struct {
	Payload *models.ComVmwareXenonCommonServiceErrorResponse
}

func (o *PutProjectsIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /projects/{id}][%d] putProjectsIdNotFound  %+v", 404, o.Payload)
}

func (o *PutProjectsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComVmwareXenonCommonServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
