package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vmware/vic/lib/apiservers/portlayer/models"
)

/*GetVCHInfoOK retrieval success

swagger:response getVCHInfoOK
*/
type GetVCHInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.VCHInfo `json:"body,omitempty"`
}

// NewGetVCHInfoOK creates GetVCHInfoOK with default headers values
func NewGetVCHInfoOK() *GetVCHInfoOK {
	return &GetVCHInfoOK{}
}

// WithPayload adds the payload to the get v c h info o k response
func (o *GetVCHInfoOK) WithPayload(payload *models.VCHInfo) *GetVCHInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v c h info o k response
func (o *GetVCHInfoOK) SetPayload(payload *models.VCHInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVCHInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
